qcubed/qcubed

- includes/base_controls/QCalendar.class.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QControlProxy.class.php
- includes/base_controls/QDataGridBase.class.php
- includes/base_controls/QDataGridColumn.class.php
- includes/base_controls/QPaginatedControl.class.php
- includes/codegen/QColumn.class.php
- includes/framework/QBaseClass.class.php
- includes/framework/QString.class.php
- includes/framework/QType.class.php
Further improvements in QDataGrid documentation. QControlProxy documentation finished. Improved QColumn's property documentation. Other random improvements in syntax and documentation too.
> Further improvements in QDataGrid documentation.

- includes/base_controls/QPaginatorBase.class.php
Adjusting PageNumber so that it does not point past the end of the item count when adjusting the item count down. This lets you point to an arbitrarily large page number, then set the item count to have the last page appear.
Its a bug either way, because the paginator will show 3 pages, but no content if pageNumber is too big.
> bugfix-Pagintor Last Page

- includes/base_controls/_actions.inc.php
Action to toggle class on an object.
> feature-ToggleClassAction

- includes/framework/QEmailServer.class.php
Using config file for temp directory rather than hardcoded value.
> bugfix-EmailTmpDir

- includes/base_controls/QSimpleTableColumn.class.php
Adding scope attribute to table headers
> feature-ScopeAttribute

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QDataGridBase.class.php
Minor refactor fixes. In particular, so many controls set strCssClass, that I needed to put it back.
> bugfix-RefactorFixes

- includes/base_controls/QCheckBox.class.php
Fixing RenderLabelAttributes to correct display problem.
> bugfix-CheckboxDisplay

- includes/base_controls/QControlBase.class.php
> feature-WrapperUtilities

- includes/base_controls/QTextBoxBase.class.php
> Minor updates to formatting in QTextBoxBase.class.php

- includes/base_controls/QTextBoxBase.class.php
Removed ValidateTrimmed Property from QTextBoxBase as discussed in #610
> Removed ValidateTrimmed Property from QTextBoxBase

- assets/js/qcubed.js
- includes/base_controls/QCheckBox.class.php
- includes/base_controls/QCheckBoxList.class.php
- includes/base_controls/QListBoxBase.class.php
- includes/base_controls/QRadioButton.class.php
- includes/base_controls/QRadioButtonList.class.php
- includes/base_controls/QTextBoxBase.class.php
Refactoring formObjChanged to move to qcubed.js implementation.
> feature-formObjChangedRefactor

- assets/js/qcubed.js
> feature-qcubedJsCleanup

- assets/js/qcubed.autocomplete.js
- assets/js/qcubed.js
- includes/base_controls/QAutocompleteBase.class.php
Fixing some recent issues introduced in Autocomplete that caused problems with filters. Had to break out into a separate javascript file again.
> bugfix-Autocomplete

- assets/php/examples/other/datagrid_connectors.php
- assets/php/examples/other/datagrid_connectors.tpl.php
- assets/php/examples/other/form_drafts.php
- assets/php/examples/other/model_connectors.php
- includes/base_controls/QLabel.class.php
- includes/base_controls/_enumerations.inc.php
- includes/codegen/templates/db_orm/drafts/_qpanel_edit.tpl.php
- includes/tests/qcubed-unit/ModelConnectorTests.php
- install/project/generated/meta_base/_readme.txt
- install/project/includes/codegen/templates/_README.txt
- install/project/includes/configuration/codegen_settings.xml
- travis/codegen_settings.xml
Changing more instances of meta and MetaControl
> bugfix-MoreMeta

- includes/base_controls/QListItemManager.trait.php
Preventing possible crash for lists the have a data binder.
> bugfix-DataBinderCrash

- includes/base_controls/QHtmlAttributeManagerBase.class.php
- includes/base_controls/QTextBoxBase.class.php
- includes/framework/QApplicationBase.class.php
- includes/framework/QHtml.class.php
Fixing encoding problems with text boxes. Attributes are already encoded. Newlines need to be html5 encoded.
> bugfix-textBox

- assets/js/qcubed.js
- assets/php/tests/ui_refresh.php
- assets/php/tests/ui_refresh.tpl.php
- includes/base_controls/QCheckBox.class.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QHtmlAttributeManagerBase.class.php
- includes/framework/QDateTime.class.php
- install/project/includes/controls/QControl.class.php
Preventing throwing an exception when giving bad data to the QDateTime
Fixing various drawing problems with ajax and display: none
> bugfix-VariousDrawingIssues

- assets/php/_devtools/jquery_ui_gen/jq_control.php
- assets/php/_devtools/jquery_ui_gen/jq_control_gen.php
Enabling datatables to generate new style of control
> bugfix-datatablesGen

- assets/js/qcubed.js
- includes/framework/JavaScriptHelper.class.php
Fixing problem with dialog callbacks. Needed to make the decode of special items in the ajax callback go deeper.
> bugfix-DialogCallbacks

- assets/css/styles.css
- includes/base_controls/QCheckBoxList.class.php
Improving formatting checkbox lists to comply with current html standards. The single-column list was not working well either, so went back to the table method.
> bugfix-CheckboxList

- includes/base_controls/QFormBase.class.php
Fixing problem where a control that injected a javascript file during GetEndScript did not eventually get that file included.
> bugfix-JavascriptFileInjection

- includes/base_controls/_utilities.inc.php
Helper for rendering in templates. Designed to be used with the shorthand <?= tag. Checks for existence of the object, and also uses the PrefererredRenderMethod if it exists.
> feature-RenderHelper

- includes/base_controls/_actions.inc.php
Action to set the value of a jquery object.
> feature-SetValueAction

- install/project/includes/configuration/header.inc.php
Fixing problem with style import. Text was getting encoded improperly.
> bugfix-StylesImport

- assets/js/qcubed.js
Fixing object unpacking problem
> bugfix-UnpackingError

- includes/base_controls/_actions.inc.php
Improving the comment on event output to better tell what object the event is for.
> feature-ImprovedCommentOnEvent

- includes/qcubed/_core/base_controls/QCheckBoxList.class.php
Add functions `CheckAll()` and `UncheckAll()` to the `QCheckBoxList` class.
> QCheckBoxList - added CheckAll(), UncheckAll()

- includes/framework/JavaScriptHelper.class.php
Improving error message if json encoding fails.
> bugfix-JsonErrorMessage

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QTextBoxBase.class.php
Fixing problems with placeholder, and converting an instance of ExecuteJavascript to the new mechanism.
> bugfix-QTextBoxItems

- includes/database/QMySqliDatabase.class.php
Fix problem with flag. Defining the undocumented flag that detects whether a field is set to ON UPDATE CURRENT_TIMESTAMP
> bugfix-MYSQLI_ON_UPDATE_NOW

- includes/framework/QDateTime.class.php
Fixing problem with javascript representation of datetime object
> bugfix-DateTimeJs

- includes/framework/QApplicationBase.class.php
Fixing problem where newlines in alert text were causing javascript errors.
> bugfix-AlertNewlines

- includes/base_controls/QControlBase.class.php
Need to clear control actions after rendering them.
> bugfix-ControlActions

- assets/js/qcubed.js
Fixing problem with null passed as param, which indicates the closure has no params.
> bugfix-NullParam

- includes/base_controls/QFormBase.class.php
Adding additional search path for templates based on the object name.
> feature-TemplateSearchPath

- includes/codegen/templates/db_type/class_gen/_main.tpl.php
Creates additional arrays based on the extra fields found in the database table.
> feature-TypeFieldArrays

- assets/php/examples/includes/footer.inc.php
- assets/php/examples/view_source.php
Minor fixes to keep show source working.
> bugfix-ExamplesShowSource

- includes/base_controls/QCheckBoxList.class.php
Not drawing anything makes it impossible to draw the control later. We must at least draw a wrapper.
> bugfix-QCheckBoxListAjaxDrawing

- INSTALL.md
- install/composer.json.sample
Fixing up the beta install instructions.
> bugfix-BetaInstall

- includes/base_controls/QListItem.class.php
List Items with value of zero were not drawing correctly.
> bugfix-ZeroValueListItem

- includes/base_controls/QSimpleTableBase.class.php
Preventing error when drawing an empty table.
> bugfix-EmptyTable

- includes/base_controls/QAutocompleteBase.class.php
- includes/base_controls/QDialogBase.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QTabsBase.class.php
Fixing issues in javascript execution order to make sure events attach in the right order.
> bugfix-JsScripts

- includes/codegen/templates/db_orm/class_gen/_main.tpl.php
- includes/codegen/templates/db_orm/class_gen/array_indexers.tpl.php
Adding utility function to index an array of objects by any unique key or the private key. Helpful for speeding up access to an array.
> feature-ArrayIndexer

- includes/base_controls/_utilities.inc.php
- includes/codegen/QCodeGenBase.class.php
- includes/codegen/controls/QListControlBase_CodeGenerator.class.php
Adding a NONE option to a list that can be set to NULL. Also, adding the ability to use _indent() during codegen.
> bugfix-ListGen

- assets/php/tests/ui_basic.php
- assets/php/tests/ui_basic.tpl.php
- includes/base_controls/QCheckBoxList.class.php
- includes/base_controls/QListBoxBase.class.php
- includes/base_controls/QListControl.class.php
- includes/base_controls/QRadioButtonList.class.php
Using javascript to select items in a list, rather than redrawing the entire list control. This is implemented for QListBox, QCheckBoxList and QRadioButtonList and can serve as examples for other lists.
> feature-ImprovedListSelection

- assets/js/qcubed.js
- assets/php/examples/advanced_ajax/dialog_box.php
- assets/php/examples/advanced_ajax/dialog_box.tpl.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QDataGridBase.class.php
- includes/base_controls/QDataRepeater.class.php
- includes/base_controls/QDialogBase.class.php
- includes/base_controls/QFormBase.class.php
This changes Dialog::Message to Dialog::Alert and implements the alert as an object that is temporarily injected into the DOM, and then removed from the DOM after the dialog is closed.
> feature-InjectedDialog

- assets/js/qcubed.js
- includes/base_controls/QCheckBoxList.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QListBoxBase.class.php
Was not recording unselecting all items in a check list or multi-select list using ajax.
> bugfix-UnsetCheckList

- assets/php/tests/ui_url.php
- assets/php/tests/ui_url.tpl.php
- includes/framework/QExceptions.class.php
- includes/framework/QHtml.class.php
Create URL and Mailto URL given components of the url.
Also, fixes a problem with an undefined function exception.
> feature-MakeUrl

- includes/_devtools/Installer.php
> bugfix-InstallerChmod

- assets/php/_devtools/installer/step_3.php
- install/project/includes/configuration/configuration.inc.sample.php
> bugfix-Installer2

- composer.json
Trying a suggestion for install
> bugfix-composerSuggestion

- .travis.yml
- composer.json
Moving to a composer install plugin
> bugfix-ComposerInstall

- composer.json
Triggering the custom installer to move files.
> bugfix-TriggerInstaller

- assets/css/styles.css
- includes/framework/QDatabaseBase.class.php
Improving the way the profile output gets displayed. In particular, this will put the profiling output as an overlay on top of the web page, rather than way at the bottom. I was particularly having trouble with embedding the profiling output in an absolute div. This makes it possible to style the profiling container however you want.
> feature-ProfileDisplay.

- includes/codegen/templates/db_orm/class_gen/_main.tpl.php
Adding a stub to be able to easily add additional functions to the model through the template mechanism.
> feature-CustomModelFunctions

- includes/framework/QDateTime.class.php
Adding compare function to be used in sorting callbacks.
> feature-DateTimeCompare

- assets/php/_devtools/codegen.php
- includes/codegen/QCodeGenBase.class.php
- install/project/includes/codegen/QCodeGen.class.php
- install/project/includes/configuration/configuration.inc.sample.php
Creating a template paths array to make multiple layers of templates.
> feature-TemplatePaths

- assets/php/examples/communication/crypto.php
- includes/base_controls/_events.inc.php
- includes/codegen/templates/db_orm/class_gen/pk_support.tpl.php
- includes/framework/QModelTrait.trait.php
- includes/framework/QQuery.class.php
Documentation fixes
Making primaryKey function public
Clarifying an if-then structure.
> bugfix-MinorFixes

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
Making sure we correctly extract the base control id from a compound control id.
> bugfix-ControlId

- includes/base_controls/QSimpleTableColumn.class.php
- includes/qcubed.inc.php
Allowing OrderByClauses to be any type, not just a QQClause
Adding a Node column type
Fixing checkbox column.
> feature-SimpleTableNodeColumnAndFixes

- includes/base_controls/QSimpleTableBase.class.php
- includes/base_controls/_events.inc.php
Fixed up column adds to bottleneck through AddColumnAt.
Created ways to get and remove columns by id.
Broke out the caption to a separate function so it can be overridden by subclasses easily.
Created a QCellClick event.
> feature-SimpleTableImprovements

- includes/framework/QDatabaseBase.class.php
Allowing sql escape of arrays. Helpful for IN clauses.
> bugfix-SqlEscapeArrays

- includes/codegen/controls/_class_paths.inc.php
- includes/qcubed.inc.php
Moving autoloader paths to separate file for maintainability.
> feature-CodegeneratorPaths

- includes/codegen/QControlCategoryType.class.php
- includes/codegen/QDatabaseCodeGen.class.php
- includes/codegen/QModelConnectorEditDlg.class.php
- includes/codegen/QModelConnectorOptions.class.php
- includes/codegen/QTable.class.php
- includes/control_registry.inc.php
Created a control category type class to help clarify which controls the model connector editor has access to.
Added the ability for sql tables to get options through the model connector interface in preparation for being able to specify the listing control during code generation.
> feature-ControlCategory

- includes/base_controls/QListControl.class.php
Fixing problem with trying to match two items that are boolean 'false'.
> bugfix-FalseListItem

- includes/codegen/QCodeGenBase.class.php
Need to call some functions statically.
> bugfix-ModelProperty

- includes/base_controls/QSimpleTableColumn.class.php
Fixing problem in new Node column.
> bugfix-NodeColumn

- includes/qcubed.inc.php
> bugfix-CategoryTypePath

- includes/base_controls/QListControl.class.php
- includes/codegen/QModelConnectorEditDlg.class.php
- includes/codegen/QModelConnectorParam.class.php
Adding ability to insert items into the general category.
> feature-ModelEditorGeneralCategory

- assets/php/_devtools/plugin_manager.php
Prevent error when plugin directory is not found.
> bugfix-PluginDir

- assets/php/_devtools/codegen.php
- includes/codegen/QDatabaseCodeGen.class.php
Producing intelligible error message if the user tries to codegen before doing anything to the configuration file.
> bugfix-CodegenErrorMessage

- includes/base_controls/QFormBase.class.php
Fixing problem with js pointers to key directories
> bugfix-SubDirectory

- includes/codegen/templates/db_orm/model_connector/refresh_methods.tpl.php
Fixing problem where we were checking for empty strings on items that were not strings.
> bugfix-LoadCheck

- includes/base_controls/QControlBase.class.php
Adding PreferredRenderMethod to options for model editor
> bugfix-PreferredRenderMethodOption

- includes/base_controls/QSimpleTableBase.class.php
Adding utility function to create a node column.
> feature-CreateNodeColumn

- includes/base_controls/QSimpleTableBase.class.php
Adding a callback to fetch row parameters. Useful for codegen a list control based on a simple table.
> feature-RowParamsCallback

- includes/base_controls/QFormBase.class.php
> bugfix-LinkedNode

- includes/codegen/QCodeGenBase.class.php
- includes/codegen/QDatabaseCodeGen.class.php
Fixing template order to be in the correct order for overriding.
Making objSettingsXml a public member for use by the templates.
Code rearranging.
> bugfix-Codegen

- includes/codegen/controls/QAutocompleteBase_CodeGenerator.class.php
- includes/codegen/controls/QListControlBase_CodeGenerator.class.php
> bugfix-CodeGeneratingTypes

- includes/framework/QQuery.class.php
Adding an accessor for the node type. Helpful for codegen.
> feature-NodeTypeAccessor

- includes/codegen/QDatabaseCodeGen.class.php
- includes/codegen/QManyToManyReference.class.php
- includes/codegen/templates/db_orm/class_gen/qcubed_query_classes.tpl.php
Fixing node types of reverse reference and many-to-many references. Regular nodes were using DBTypes, but these other nodes were using PHP types.
> bugfix-NodeTypes

- includes/base_controls/QHListControl.class.php
- includes/framework/QApplicationBase.class.php
- includes/qcubed.inc.php
Fixing a few problems:
- Initializer needs to preload all files before trying to use a file that could generate an autoload
- Need to preload new base classes of the control base.
- Typo.
> bugfix-AutoLoadOrder

- includes/framework/QFolder.class.php
Making sure folder exists before reading it.
> bugfix-QFolderDirectory

- includes/base_controls/QAccordionBase.class.php
- includes/base_controls/QCheckBox.class.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QControlLabel.class.php
- includes/base_controls/QControlProxy.class.php
- includes/base_controls/QCsvTextBox.class.php
- includes/base_controls/QImageBase.class.php
- includes/base_controls/QPaginatorBase.class.php
- includes/framework/QHtml.class.php
- includes/qcubed.inc.php
- install/project/includes/controls/QPaginator.class.php
Added some documentation. No code has been altered.
> Added some documentation

- includes/database/QMySqli5Database.class.php
- includes/framework/QDatabaseBase.class.php
Added function to execute a Mysql stored procedure. Could be generalized to other DBs.
> feature-MysqlStoredProcedure

- includes/base_controls/QSimpleTableColumn.class.php
- includes/codegen/templates/db_orm/model_connector/refresh_methods.tpl.php
Making sure the internal object exists before attempting to reload it.
> bugfix-Refresh

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QListBoxBase.class.php
Removing Enabled from the ControlBase, since it is handled in the HtmlTagManager class now. The current code was preventing it from working right.
> bugfix-Enabled

- assets/php/_devtools/codegen.php
- includes/_devtools/codegen.inc.php
- includes/qcubed.inc.php
Fixing location of includes so that code generators are only included during code generation.
> bugfix-CodeGeneratorInclude

- includes/base_controls/QTabsBase.class.php
> bugfix-TabActivate

- includes/base_controls/QDialogBase.class.php
Making sure both kinds of dialog buttons can cause validation.
> bugfix-DialogButtonValidation

- includes/codegen/controls/QControlBase_CodeGenerator.class.php
- includes/codegen/controls/QListControlBase_CodeGenerator.class.php
- includes/codegen/templates/db_orm/model_connector/property_comments.tpl.php
- includes/codegen/templates/db_orm/model_connector/property_get.tpl.php
- includes/codegen/templates/db_orm/model_connector/property_set.tpl.php
Adding the ability to set the Null label on a listbox. As a result, you can now add getters and setters to the Connector from the control generator.
> feature-ListBoxNullLabel

- includes/base_controls/QCheckBoxColumn.class.php
Adding brackets and spacing for easier debugging.
> minor-CheckboxColumn

- includes/base_controls/QControlProxy.class.php
Allowing an option to turn off html entities so you can use a proxy link to wrap html.
> feature-ProxyHtmlLinks

- includes/framework/QHtml.class.php
Additional HTML utilities to create links and urls
> feature-HtmlUtilities

- includes/base_controls/QSimpleTableBase.class.php
- includes/base_controls/QSimpleTableColumn.class.php
Documentation improvements (additions and formatting) to QSimpleTableBase and QSimpleTableColumn classes.
> Documentation improvements 

- assets/css/styles.css
- assets/php/examples/includes/examples.inc.php
- assets/php/examples/includes/footer.inc.php
- assets/php/examples/view_source.php
Fixing examples to correctly show multiple examples from plugins. Specifically for bootstrap plugin at this point. Not the prettiest code, but works for now.
> bugfix-PluginExamples

- includes/base_controls/QDateTimePicker.class.php
- includes/base_controls/QSimpleTableColumn.class.php
Fixing QDateTimePicker class time handling bug.
> Fixing QDateTimePicker class time handling bug

- includes/base_controls/QRadioButtonList.class.php
- includes/framework/QHtml.class.php
Cleanup and adding some features to allow bootstrap styling.
> bugfix-RadioList

- includes/base_controls/QFormBase.class.php
Fixing broadcast of watched changes
> bugfix-WatcherAjax

- includes/base_controls/QFormBase.class.php
Adding ability to use any form id you want.
> bugfix-CustomFormId

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
- includes/watchers/QWatcherBase.class.php
- includes/watchers/QWatcherCache.class.php
- includes/watchers/QWatcherDB.class.php
Fixing watcher to broadcast changes correctly. Old version was broadcasting too often, causing significant performance problems.
> bugfix-WatcherFixes

- includes/framework/QTimer.class.php
Fixing static functions to be overridable.
> bugfix-QTimerOverride

- includes/base_controls/_utilities.inc.php
Fixing block render function for new HTML5 encoding.
> bugfix-BlockRender

- assets/php/tests/ui_paginator.php
- assets/php/tests/ui_paginator.tpl.php
- includes/base_controls/QPaginatorBase.class.php
- includes/base_controls/QSimpleTableColumn.class.php
Fixing paginator numbers at index count boundary. Added UI test case.
> bugfix-PaginatorNumbers

- includes/framework/QQuery.class.php
Adding EXISTS standard SQL condition
> feature-ExistsCondition

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
- includes/watchers/QWatcherBase.class.php
- includes/watchers/QWatcherCache.class.php
Another attempt at fixing the watchers. Trying to make sure that changes in one window will cause watchers to change in another window, even when first window did not have watched controls showing.
> bugfix-Watchers3

- includes/base_controls/QHListControl.class.php
- includes/framework/QCryptography.class.php
Making the QCyrptography class serializable so it can be used in form objects.
> bugfix-QCryptographySerialization

- includes/error.inc.php
- includes/framework/QInstallationValidator.class.php
- includes/framework/QString.class.php
Fixing up some problems so that we can get a reasonable error message if prepend.inc is not getting loaded for some reason.
> bugfix-NoPrependErrors

- includes/framework/QCryptography.class.php
Fixing regression problem, decrypt not the same as encrypt
> bugfix-Crypto2

- assets/php/_devtools/installer/index.php
- assets/php/_devtools/installer/step_1.php
- assets/php/_devtools/installer/step_2.php
- assets/php/_devtools/installer/step_3.php
https://github.com/qcubed/app-starter/issues/10
Seems that the `_p` function's default behavior has changed.
> Fixes the app-starter issue

- includes/database/QSqlServer2005Database.class.php
> Notice when generating with error

- includes/codegen/templates/db_orm/panels/list_edit_item.tpl.php
> Fixes the issue #860 (The `two_key` list example is broken)

- includes/base_controls/QFormBase.class.php
Fixes to handle the unique way that TreeNav delivers ajax events. Allows other potential controls to be able to directly send ajax events and then look for the result in the ParsePostData function.
> bugfix-TreeNavIssues

- assets/php/examples/other_controls/persist.php
Fixes bug caused by defaulting Redirect to interrupt the current script.
> bugfix-PersistExample

- includes/framework/QQuery.class.php
- includes/tests/qcubed-unit/BasicOrmTests.php
Fixing expansion problem. Includes unit test. Fixes #891
> bugfix-PartialQueryExpansion

- includes/framework/QInstallationValidator.class.php
Making the QCubed_Upload define optional
> bugfix-QCubedUploadOption

- includes/base_controls/QControlProxy.class.php
Adding ability to turn off entities for proxy buttons.
> feature-ProxyEntities

- includes/codegen/controls/QDataGrid2Base_CodeGenerator.class.php
Making sure data grid gets modified when setting conditions or clauses.
> bugfix-QDataGrid2ModifyFlag

- includes/base_controls/QSimpleTableBase.class.php
A very minor feature. Functions to hide and show columns without having to remove them from the grid completely.
> feature-HideShowColumns

- includes/base_controls/QHtmlAttributeManagerBase.class.php
Adding ability to remove css classes by prefix.
> feature-RemoveCssClassByPrefix

- includes/base_controls/QSimpleTableColumn.class.php
Fixing problem with Col tag. CssClass should only be applied to cell and not col also. There is another way to make a col tag class.
> bugfix-ColTag

- includes/framework/QQuery.class.php
Fixing an HHVM problem. Latest version of HHVM appears to choke on testing for empty on the alias.
> bugfix-HHVMproblem

- includes/qcubed.inc.php
Autoloader for QDialog_ButtonEvent
> bugfix-DialogButtonEventAutoload

- includes/database/QMySqlDatabase.class.php
- includes/database/QMySqliDatabase.class.php
- includes/database/QSqLite3PdoDatabase.class.php
Adding one to length of decimal columns, since the column should allow a decimal point in addition to the digits.
Fix for #921
> bugfix-DecimalColumnLength

- includes/base_controls/QHListControl.class.php
Adding option to encrypt the control's values, rather than making it mandatory.
> feature-OptionalHListEncryption

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
Adding ability for originating control to process return values from actions before handing them off to the action function. This can be used to decrypt encrypted values for example.
Also, expands the action function parameter list to take an optional extra parameter which has all the information on the action, including the action itself. The action encapsulates the event, so its easy to get all the information needed to process complex actions.
Additional cleanup.
Completely compatible with prior interface.
> feature-TriggerMethodImprovements

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QControlProxy.class.php
Preventing proxies from auto-rendering, which currently throws an exception. This will allow proxies to be included in an auto-rendered control.
> bugfix-AutoRenderedProxies

- assets/js/qcubed.js
- includes/framework/QApplicationBase.class.php
Set cookie function that works in both Ajax mode and Server mode.
> feature-SetCookie

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
- includes/framework/QQuery.class.php
Minor speed improvements and comment
> enhancement-MinorSpeedImprovements

- includes/base_controls/QDataGrid2Base.class.php
Making sure caption string gets included in the caption tag, along with paginator.
> bugfix-DataGrid2Caption

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
Adding ability for an action method to be a static method in a class.
Usage:
$obj->AddAction (new QClickEvent(), new QAjaxAction ('ClassName::MethodName'));
Also doing some commenting.
> feature-StaticActionMethod

- includes/base_controls/QDataGrid2Base.class.php
Added the ability to get the checked ids from a checkbox column if one exists.
Also added the ability to specify a specific column to clear checkboxes.
And, commented the entire class.
> feature-CheckedIds

- includes/base_controls/QPaginatorBase.class.php
Refactoring of the paginator to make it easier to maintain, and easier to create subclasses.
Tested against the assets/php/test/ui-paginator.php test.
> bugfix-PaginatorRefactor

- includes/base_controls/QControlProxy.class.php
Fixing extraneous plus signs that got into code.
> bugfix-RenderAsScripts

- includes/codegen/templates/db_orm/panels/edit_validate_unique.tpl.php
Preventing a validation check for unique reference if the control was not created.
> bugfix-UniqueValidation

- assets/php/examples/includes/examples.inc.php
- assets/php/examples/qcubed_query/qqfuncnmath.php
- includes/framework/QQuery.class.php
- includes/tests/qcubed-unit/QQFuncTest.php
- includes/tests/qcubed-unit/QQMathOpTest.php
are added to ensure this stuff to work
> Tests, fixes and example

- includes/base_controls/QSimpleTableBase.class.php
- includes/base_controls/QSimpleTableColumn.class.php
Fixing some typos
Also fixing a problem with extracting a property list in a link column.
> bugfix-LinkColumnPropertyList

- assets/php/examples/qcubed_query/qqfuncnmath.php
- includes/framework/QQuery.class.php
- includes/tests/qcubed-unit/QDateTimeTest.php
- includes/tests/qcubed-unit/QQFuncTest.php
- includes/tests/qcubed-unit/QQMathOpTest.php
Added the ability for the new MathFunc to work on a unary operator, and added the QQ::Neg function for the standard negative operator.
> feature-Unary operator

- includes/qcubed.inc.php
> bugfix-LinkColumnAutoLoad

- assets/js/qcubed.js
- assets/php/examples/plugins/components.php
- assets/php/examples/plugins/packaging.php
- includes/base_controls/QCheckBox.class.php
- includes/base_controls/QCheckBoxList.class.php
- includes/base_controls/QDraggableBase.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QRadioButton.class.php
- includes/base_controls/QRadioButtonList.class.php
- includes/base_controls/QResizableBase.class.php
- includes/base_controls/QTabsBase.class.php
Did some refactoring and simplification of the core QCubed.js code. Brought the server and ajax code into alignment as much as possible so they share much of the same code. Simplified the handling of checkable controls. Using built-in javascript and PHP functions to handle encoding of the ajax post data, rather than encoding it by hand. Added documentation.
> feature-QCubedJSRefactor

- assets/js/qcubed.autocomplete.js
Not detecting a change correctly. Was preventing the text portion of the autocomplete from updating.
> bugfix-AutocomplateChange

- assets/js/qcubed.js
- includes/base_controls/QSimpleTableBase.class.php
- includes/base_controls/QSimpleTableColumn.class.php
Adjustments to allow new checkable control scheme to work on checkbox column
> bugfix-CheckboxColumnCheckableControls

- includes/base_controls/QBlockControl.class.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QDataRepeater.class.php
- install/project/includes/app_includes/nav_panel.class.php
A regression fix for the previous template location bugfix.
> bugfix-TemplateLocation2

- includes/base_controls/QSimpleTableBase.class.php
- includes/base_controls/QSimpleTableColumn.class.php
Adding ability to send a QQNode to a link column to specify the text, link parameters, or QControlProxy action param.
> feature-QQNodeForLinkColumn

- install/project/includes/app_includes/nav_panel.class.php
> bugfix-NavPanelLocation

- includes/base_controls/QSimpleTableBase.class.php
Regression fix for when there are no columns. Was getting invalid data sent to foreach.
> bugfix-SimpleTableRegression

- includes/base_controls/QSimpleTableColumn.class.php
Fixing problem with cell not showing a zero '0'
> Fixing error where the value '0' was not appearing in a cell.

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QDataGrid2Base.class.php
- includes/base_controls/QDataGridBase.class.php
- includes/base_controls/QPaginatedControl.class.php
Moving knowledge of derived control out of QPaginatedControl and adding some documentation.
> bugfix-minorRefactorAndDoc

- assets/php/_devtools/start_page.php
Update utility seems to have been removed already. Removing the link from start page. Solves #625
> Removed the updater link

- includes/base_controls/QBlockControl.class.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QDataRepeater.class.php
Making sure we look in all the likely places to find a potential template. Another regression fix.
> bugfix-TemplatePath3

- assets/js/qcubed.js
- includes/base_controls/QFormBase.class.php
- includes/framework/QApplicationBase.class.php
Fixes some problems that occur when the session is lost, or when there is no local storage enabled.
> bugfix-AjaxProcessing

- includes/qcubed.inc.php
> bugfix-QJsFunctionAutoLoad

- includes/framework/QInstallationValidator.class.php
Removing zip extension as an installation requirement. Fixes #1003.
> bugfix-ZipExtension

- includes/base_controls/QFormBase.class.php
Instead of attaching events to every control, we now attach one event to the form for the designer. A bit of a hack, but only when we are in designer mode. The old way was creating way too much code for busy forms. This new way changes very little, and now allows right clicking on labels and anything inside of a control wrapper.
> bugfix-DesignerImprovement

- install/project/includes/configuration/configuration.inc.sample.php
> docfix-UPLOAD

- assets/php/examples/events_actions/javascript_alerts.tpl.php
Fixing reference to obsolete dialog plugin. Fixes #887
> bugfix-DialogExampleReference

- includes/base_controls/QFormBase.class.php
Removing unused function IsCheckableControlRendered. Commenting CheckableControlValue function.
> bugfix-RemoveIsCheckableControlRendered

- includes/base_controls/QCheckBox.class.php
Adding editor parameters to checkbox
> bugfix-CheckboxEditor

- includes/codegen/QModelConnectorEditDlg.class.php
Fixing code regeneration problem
> bugfix-CodeRegeneration

- assets/php/qcubed_unit_tests.php
- includes/tests/qcubed-unit/QTestForm.tpl.php
Fixing unit tests to describe the setup required before executing the tests locally.
> bugfix-UnitTestSetup

- composer.json
- includes/base_controls/QDataGrid2Base.class.php
- install/project/includes/configuration/configuration.inc.sample.php
Making FontAwesome installable as an option. FontAwesome is now open-source licensed for general use.
> bugfix-QDataGrid2Font

- assets/php/examples/includes/examples.inc.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QSimpleTableColumn.class.php
- includes/base_controls/_events.inc.php
Fixing parameter order of QOnEvent, and some language around the usage of it.
> bugfix-QOnEventParamOrder

- includes/base_controls/QDataGridLegacyBase.class.php
- includes/base_controls/QDataGridLegacyRowStyle.class.php
- includes/base_controls/QTagStyler.class.php
After making this change creating QDataGridLegacy works for me.
> Updated instances of QDataGridRowStyle to QDataGridLegacyRowStyle

- includes/base_controls/QFormBase.class.php
- includes/codegen/QModelConnectorEditDlg.class.php
Fixing right click to work with server posts as well as ajax posts.
Fixes #1035.
> bugfix-EditorDialogAndServerPosts

- includes/base_controls/QCheckBoxLegacyColumn.class.php
- includes/base_controls/QDataGridLegacyBase.class.php
- includes/base_controls/QDataGridLegacyColumn.class.php
- install/project/includes/controls/QDataGridLegacy.class.php
More changes to move old DataGrid code to Legacy status
> bugfix-MoreDataGridLegacy

- includes/base_controls/_events.inc.php
Fixing problem when specifying click parameters using an array
> bugfix-CellClickMultiParam

- includes/base_controls/QDatepickerBoxBase.class.php
Adding min and max text validation messages.
> feature-MinMaxDateMessages

- assets/css/styles.css
- assets/js/qcubed.js
- assets/php/error_dump.php
- assets/php/error_page.php
- install/project/includes/configuration/configuration.inc.sample.php
Improved error handling:
- Added ability to be emailed when errors occur.
- Moved things in the configuration file to group error handling
- Made error dialog NOT dependent on Jquery UI dialog.
- Fixed problem where error dialog was showing html for friendly error page.
> feature-ErrorHandlingImprovements

- includes/codegen/controls/QHtmlTable_CodeGenerator.class.php
Fixing comment to match variable name
> bufix-ConditionComment

- includes/error.inc.php
Fixing the PHP7 Error for error.inc.php
Refers #1048
> Fixing the PHP7 Error for error.inc.php

- includes/codegen/templates/db_orm/class_gen/object_delete.tpl.php
- includes/codegen/templates/db_orm/class_gen/object_save.tpl.php
Changed the codegen template files so that the database name isn't hard coded. This will fix problems where the database names are different between the development and production environments.
* My first pull request ever!!!!  :)
> fixed codegen template db name hardcoded

- includes/error.inc.php
Breaking out the code that creates a backtrace so it is usable in other debug situations by the programmer.
> feature-Backtrace

- assets/php/examples/communication/crypto.php
> fixing QCrypto Example

- includes/framework/QCryptography.class.php
- includes/tests/qcubed-unit/QCryptoTest.php
Fixing to make sure IV's are randomly generated always, and providing a mechanism to allow values to be decrypted without needing to save the IV, but rather providing the IV with the encrypted data. Also added unit tests and documentation.
> bugfix-QCrypto

- assets/js/qcubed.js
Fixing minor js error when dialog has no default button.
> bugfix-minorJsProblem

- includes/base_controls/QDataGridBase.class.php
Minor feature to save the information to sort a grid, and later restore it.
> feature-SortInfo

- includes/base_controls/QAutocompleteBase.class.php
Giving the ability for the designer to turn off autoload for autocompletes
> bugfix-AutocompleteAutoload

- includes/base_controls/QHtmlTableBase.class.php
Making it possible to send parameters to the Callable column's callback.
> feature-CallableColumnParams

- includes/framework/QQuery.class.php
- includes/tests/qcubed-unit/BasicOrmTest.php
#1037 posted to v3 and with test case.
> bugfix-SubSql

- includes/qcubed.inc.php
Adding autoloader for virtual attribute column. Prevents error messages from popping up.
> bugfix-VirtualAttributeColumnAutoLoader.

- README.md
I changed it to correctly go to the right file
> 404 on INSTALL.md

- includes/base_controls/QHtmlTableColumn.class.php
Allow embedding of click event proxy into a sub-item of the cell.
> bugfix-HeaderColumnNum

- includes/base_controls/QControlProxy.class.php
Minor fix to allow settting null options when you are simply trying to turn off html entities.
> bugfix-NullProxyOptions

- README.md
updating the examples link in the README.md file.
> updated examples link

- includes/qcubed.inc.php
- index.php
Updating version number and updated the path in index.php by default. Also checked for usage of `framework` in the code. No other references need updating.
> Updating version number and updated the path in index.php by default

- includes/framework/QHtml.class.php
Added a few features to the mailto url, including specifying an alternate name.
> feature-MailToUrlWithName

- includes/codegen/templates/db_orm/class_gen/property_getters_setters.tpl.php
Fixing some comments and checking for not-null status for items that are not null in the database.
> bugfix-NotNull

- docs/Strings/README.md
- includes/framework/QCryptography.class.php
- includes/framework/QString.class.php
Changes:
- Move the methods to QString class.
- Documentation 
Solves #1160
> Refactor Base64Encode and Base64Decode methods in QCryptography

- assets/css/styles.css
- includes/codegen/controls/QHtmlTable_CodeGenerator.class.php
Fixing List generators to prevent a problem when clicking on rows that are supposed to create actions.
> bugfix-DebounceTableRows

- includes/codegen/templates/db_orm/class_gen/property_getters_setters.tpl.php
Fixing problem with getting data from a Type model. We were generating the wrong variable name.
> bugfix-TypeModelGeneration

- includes/framework/QString.class.php
GetRandomString method in QString is new and facilitates the feature
It returns a string of a given length, the characters of which are extracted
from the character set supplied as the second argument and are in random
order. In case a character set is not supplied, alphanumeric character set
is used by default.
> Generate random string of a given length from a character set

- assets/css/styles.css
Making sure we have a pointer rather than a cursor for clickable rows.
> bugfix-ClickableRowPointer

- includes/codegen/templates/db_orm/model_connector/save_object.tpl.php
- includes/codegen/templates/db_orm/panels/edit_create_objects.tpl.php
Fixing some code generation issues when the connector editor specifies that no object should be created.
> bugfix-ConnectorCodeGenerator

- includes/framework/QHtml.class.php
Feature to quickly create an html table from an array of data.
> feature-HtmlTable

- includes/base_controls/QDataRepeater.class.php
Fixing some names for the callback parameters
> bugfix-DataRepeaterCallbackName

- includes/qcubed.inc.php
- includes/qform_state_handlers/QRedisBackedFormStateHandler.class.php
- install/project/includes/configuration/configuration.inc.sample.php
Redis Formstate Handler completed. Tested and works for me.
@matthiaz You were interested in this feature. Can you please test and tell us if it works well enough?
> Redis Formstate Handler completed

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/_actions.inc.php
Cleaning up form code surrounding FormAttributes.
> bugfix-FormAttributes

- includes/codegen/templates/db_orm/class_gen/property_comments.tpl.php
- includes/codegen/templates/db_orm/class_gen/property_get.tpl.php
- includes/codegen/templates/db_orm/class_gen/property_getters_setters.tpl.php
- includes/codegen/templates/db_orm/class_gen/property_set.tpl.php
- includes/tests/qcubed-unit/BasicOrmTest.php
Fixing ability to retrieve a Type value as a string from a model object.
Removes rendundant code for getting a Type value.
Also fixing some comments to use better English.
> bugfix-GetTypeString

- includes/base_controls/QFormBase.class.php
> bugfix-FormRegression

- includes/base_controls/QDialogBase.class.php
Fixing dialog visibility problem for old way of doing dialogs.
> bugfix-DialogVisibility

- assets/php/_devtools/jquery_ui_gen/jq_control.php
- includes/codegen/QCodeGenBase.class.php
- install/project/includes/configuration/codegen_settings.xml
Removing unused template escape setting
> bugfix-RemovingTemplateEscape

- includes/base_controls/QDialogBase.class.php
Fixing up dialog visibility problem
> bugfix-DialogDisplay

- assets/js/qcubed.js
Fixing problem with executing javascript functions as commands
> bugfix-JsFunctions

- includes/framework/QString.class.php
The function is renamed from 'GenerateSlug' to 'SanitizeForUrl'
Indentations are verified.
> Renewed commits  'SanitizeForUrl'

- install/project/includes/app_includes/app_includes.inc.php
Fixing bad comment. Fixes #677
> bugfix-AppIncludeComment

- includes/qform_state_handlers/QDbBackedFormStateHandler.class.php
> bugfix-DbBackedFormStateHandlerComment

- includes/codegen/templates/db_orm/class_gen/index_load_array_manytomany.tpl.php
- includes/codegen/templates/db_orm/class_gen/instantiation_methods.tpl.php
- includes/codegen/templates/db_orm/class_gen/object_save.tpl.php
- includes/codegen/templates/db_orm/class_gen/pk_support.tpl.php
Fixing some warnings in the doc blocks of generated code. Adding hints for object types.
> bugfix-CodegenDocBlocks

- includes/framework/QHtml.class.php
Adds the ability to pass in a URL, and have that URL modified by the given parameters.
> feature-MakeUrlImprovements

- assets/php/examples/datagrid/qcheckboxcolumn.php
> bugfix-1152

- includes/codegen/templates/db_orm/panels/_edit_base.tpl.php
Requiring the model connector file before using it.
> bugfix-CompareModelConnector

- includes/codegen/templates/db_orm/class_gen/property_getters_setters.tpl.php
- includes/tests/qcubed-unit/BasicOrmTest.php
Fixing regression. Its too difficult to require a default value for model fields.
> bugfix-NullSetter

- includes/base_controls/QControlBase.class.php
Adding OnClick standard action handler and fixing up some type checking to use built-in type checking.
> feature-OnClick

- includes/base_controls/_events.inc.php
Fixing documentation for OnEvent, since it is useful for any event that we do not specifically have our own event handler for.
> bugfix-EventDoc

- includes/codegen/controls/QHtmlTable_CodeGenerator.class.php
Fixing comment for making a row editable
> bugfix-EditableRowComment

- includes/framework/QApplicationBase.class.php
Per conversations regarding dependency injection, this is adding the ability to make an application object constructor in preparation for using it as a service repository or other container for application wide singletons.
> feature-ApplicationConstructor

- includes/codegen/templates/db_orm/class_gen/associated_object_manytomany.tpl.php
Adds the ability to check if an object is associated by checking the key. Complements the association by key function.
> feature->IsAssociatedByKey

- includes/base_controls/QCalendar.class.php
- includes/base_controls/QJsTimerBase.class.php
Fixing signature for AddAction for controls that override this.
> bugfix-OnClickRegression

- assets/php/examples/mysql_innodb.sql
- includes/base_controls/_actions.inc.php
- includes/codegen/QModelConnectorOptions.class.php
- includes/framework/JavaScriptHelper.class.php
- includes/framework/QTimer.class.php
- includes/tests/qcubed-unit/QTestForm.tpl.php
Minor typos, moving an action to the actions file.
> bugfix-Minor

- assets/php/examples/datagrid/rowactions.php
Fixing example to not choke on clicks on the header
> bugfix-RowClickExample

- includes/base_controls/_actions.inc.php
Fixing problem where actions that block and that also get a delay were not firing.
> bugfix-BlockingAndDelayedActions

- includes/codegen/templates/db_orm/forms/_qform_list.tpl.php
- includes/codegen/templates/db_orm/forms/edit_protected_member_variables.tpl.php
> bugfix-strObjectName

- includes/codegen/QTypeTable.class.php
- includes/codegen/controls/QListControlBase_CodeGenerator.class.php
- includes/codegen/templates/db_type/class_gen/_main.tpl.php
- includes/tests/qcubed-unit/QTypeTest.php
Fixed code generation of type table lists so that the text is translatable.
Fixes #1274
> bugfix-TypeTableTranslation

- assets/php/profile.php
The devtools especially the profile.php file has several security issues. You cold remove it as part of your deploy to production, but lets make sure that profile.php cannot run without having EnableProfiling turned on on the database in question.
> Fix security issue profiler

- includes/codegen/QCodeGenBase.class.php
https://github.com/qcubed/qcubed/issues/1307
> adding strtolower

- assets/css/styles.css
- assets/php/_devtools/installer/step_2.php
- assets/php/_devtools/installer/step_3.php
- install/project/includes/configuration/configuration.inc.sample.php
With every installation qcubed generated a faulty configuration file. The "onlyfullgroupby" thingy didn't get replaced. I fixed that while keeping most of the code that runs this. I'd to refactor it even more at some point, but not now. 
I've also added the ability to set the timezone during the installation.
> Improving the installation and removing 2 year old bug.

- assets/php/examples/events_actions/common_handlers.php
- assets/php/examples/events_actions/common_handlers.tpl.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/_events.inc.php
as mentioned in : https://github.com/qcubed/qcubed/issues/1224 
I added a couple of common event handlers and updated the documentation ( I hope I did this correctly)
> Adding common event handlers
