- includes/base_controls/QSimpleTableColumn.class.php
- includes/codegen/QMetaEditDlg.class.php
Since we cannot store closures in the form state, I am changing the name and type hint for this column.
> Bugfix-QSimpleTableClosure to Callable

- includes/base_controls/QCheckBox.class.php
- includes/base_controls/QCheckBoxList.class.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QCsvTextBox.class.php
- includes/base_controls/QDateTimePicker.class.php
- includes/base_controls/QDateTimeTextBox.class.php
- includes/base_controls/QDatepickerBoxBase.class.php
- includes/base_controls/QFileAssetBase.class.php
- includes/base_controls/QFileControl.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QListBoxBase.class.php
- includes/base_controls/QNumericTextBox.class.php
- includes/base_controls/QRadioButtonList.class.php
- includes/base_controls/QTextBoxBase.class.php
- includes/base_controls/QTreeNav.class.php
- install/project/includes/controls/QImageFileAsset.class.php
Changing the setting of the validation error to the attribute. Fixing a problem where setting the validation error from within controls by just setting the text did not cause a redraw.Also, make a distinction between Errors and Warnings for CSS frameworks.
> bugfix-ValidationErrorRedraw

- includes/codegen/templates/db_orm/meta_control/refresh_methods.tpl.php
- includes/framework/QBaseClass.class.php
- includes/framework/QExceptions.class.php
Fixes a problem where a template that calls a non-existant method would cause codegen to return a blank page, rather than an error code.
Also restored title on load of metacontrol.
> bugfix-CodegenErrors

- assets/php/examples/basic_qform/hlist.php
- assets/php/examples/basic_qform/hlist.tpl.php
- assets/php/examples/basic_qform/listbox.php
- assets/php/examples/basic_qform/listbox.tpl.php
- assets/php/examples/includes/examples.inc.php
- assets/php/tests/ui_basic.php
- assets/php/tests/ui_hlist.php
- assets/php/tests/ui_hlist.tpl.php
- includes/base_controls/QAutocompleteBase.class.php
- includes/base_controls/QCheckBoxList.class.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QDataBinder.trait.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QHListControl.class.php
- includes/base_controls/QHListItem.class.php
- includes/base_controls/QHtmlAttributeManagerBase.class.php
- includes/base_controls/QHtmlList.class.php
- includes/base_controls/QListBoxBase.class.php
- includes/base_controls/QListControl.class.php
- includes/base_controls/QListItem.class.php
- includes/base_controls/QListItemBase.class.php
- includes/base_controls/QListItemManager.trait.php
- includes/base_controls/QListItemStyle.class.php
- includes/base_controls/QPaginatedControl.class.php
- includes/base_controls/QRadioButtonList.class.php
- includes/base_controls/_enumerations.inc.php
- includes/framework/QCryptography.class.php
- includes/framework/QExceptions.class.php
- includes/qcubed.inc.php
My latest take on this. Many competing goals:
1. Reducing code duplication
2. Use new drawing base code
3. Create a common API as much as possible for the QListControl and the QHListControl
4. Simplify
This is my best balance between these. There are a number of new base controls to prevent too much overloading of functionality in controls that don't need it. That came at the cost of some complexity, but it shouldn't be too difficult to follow.
Added some functionally along the way. There is now a QDataBinder trait sharing the data binding code between paginated controls and the QHListControl, and that can be re-used in other future controls if needed. Changed the QHtmlList to QHListControl to better reflect that it is a hierarchical list. And, HTML list was just not very descriptive …
> feature-ListItemRefactor

- includes/base_controls/QControlBase.class.php
Quite a few times, we need a panel/control to call a method in that control/panel's  parent. This can be done in cases where a functionality which we need to handle in the parent is to be delegated to child controls. However, sometimes, it might be needed that a child panel be moved into another panel within the parent. In such cases, calling the parent's delegated method will fail.
The best example here would be our AJAX dashboard. When we save an edit (or cancel one), we call a method on the panel which tells its parent (which is a QForm) to close itself. However, if we try to move this functionality into a panel, it will fail because the new parent will not have the method to close the edit panel. 
The new method added can help in such cases. The child panel can now search for the …
> Search parent control hierarchy/lineage by a given method name.

- assets/js/qcubed.js
- assets/php/tests/ui_js_inject.php
- assets/php/tests/ui_js_inject.tpl.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QTextBoxBase.class.php
- includes/base_controls/QWaitIcon.class.php
- includes/base_controls/_enumerations.inc.php
- includes/framework/JavaScriptHelper.class.php
- includes/framework/QApplicationBase.class.php
Refactoring sending of commands to javascript widgets. This work paves the way to eventually removing the eval in qcubed.js. This is an intermediate step in the process, but one that is a good milestone for testing.
Fixed a couple of things in the Examples code during testing.
Added an independent test of the new javascript file injection mechanism. The new mechanism allows injected files to be loaded in parallel, and for some ajax processing to occur while the load is happening as well, overall improving ajax performance in these special situations.
> feature-RefactoringAjaxCommands1

- includes/configuration/configuration.inc.php.sample
- includes/qcubed/_core/base_controls/QFormBase.class.php
This change adds a new configuration option called `__PRELOAD_JS_FILES__`, which allows loading the javascript files with `<script>` tags rather than with `qc.loadJavaScriptFile`.
The current approach of loading control-specific (including plugin) javascript files with `qc.loadJavaScriptFile` creates lots of problems when debugging with firebug or chrome.
By default this flag is off, so the change is fully backward compatible.
The big block of code that shows as a diff, is not new, it's just moved up within the same function.
> add a configuration option to load the javascript files with <script> tags

- includes/base_controls/QControlBase.class.php
This is a bugfix for GetControlFromHierarchyByMethodName in QControlBase which I discovered after putting it in different places.
> BugFix for GetControlFromHierarchyByMethodName in QControlBase

- includes/codegen/templates/db_orm/class_gen/_main.tpl.php
- includes/codegen/templates/db_orm/class_subclass/_main.tpl.php
Changing default watcher state to true for all generated classes. Will not do anything until a watcher class is defined, but this fixes a bug showing up on the examples page, and an annoying problem as you turn watchers on.
> bugfix-DefaultWatcherToTrue

- includes/codegen/templates/db_orm/class_gen/instantiation_methods.tpl.php
- includes/framework/QDatabaseBase.class.php
Fixing a very corner case problem. There is a commented out Initialize function generated for all the Models. If you uncomment that, it will automatically initialize to default values. The problem occurred when the value in the database was a null, but the default value was not null. In that case, the default value would be put in the loaded object, rather than the null in the database.
This fix also improves performance on larger tables by avoiding the array_key_exists calls and rather using only isset, which is faster, and is exponentially faster as the table gets bigger.
> bugfix-DbNullHandling

- includes/framework/QQuery.class.php
- includes/tests/qcubed-unit/QTypeTests.php
Fixing QQ::Between to accept any type of data that is convertible to a SQL value, rather than just strings.
> bugfix-QQBetweenTypes

- includes/framework/QDateTime.class.php
When adding months, if the day is at the end of the month, there is a possibility that this will cause the add month to roll over to the beginning of the next month. This make an adjustment so that it will just go to the end of the correct month. In other words, if you add one month to January 31, this will make sure the date is February 28, and not March 3.
> bugfix-AddMonth

- includes/base_controls/QFormBase.class.php
- install/project/includes/configuration/header.inc.php
Fixing style sheet import to use a link when included in the head. Closing an open quote. 
There is a way to use a link in the body, but its HTML5 only at this point, so I thought keeping the old way when not in the head would be good for backward compatibility for now.
> bugfix-ImportStyleSheets

- includes/qcubed/_core/_devtools_cli/codegen.inc.php
This fixes the codegen CLI tool. However it changes the required command line argument: it used to require the path to the `codegen_settings.xml` file. But that was clearly not enough since the script used `__CONFIGURATION__` and `__QCUBED__` and some other settings. Thus the new version requires the path to the project base directory.
> fix codegen CLI. Fixes #520

- assets/js/qcubed.js
- assets/php/tests/ui_basic.php
- assets/php/tests/ui_basic.tpl.php
- includes/base_controls/QCheckBox.class.php
- includes/base_controls/QCheckBoxList.class.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QImageButton.class.php
- includes/watchers/QWatcherDB.class.php
Fixing up some html validation errors:
- Checkboxes must have a value attribute. Required doing checkbox lists a little differently.
- "for" attribute in labels must point to an actual form control
- Name field in img tags is deprecated
- QWatcherDB was inserting a tab into the html. Removed trailing php tag to fix permanently.
> bugfix-htmlValidationErrors

- includes/base_controls/QFormBase.class.php
- includes/framework/QApplicationBase.class.php
Rearranging where javascript commands output so that they can be executed during form create. Fixing a problem that wherbey if you set an option in a control that needed to execute a javascript command to set something in the corresponding html widget, it would not work because the widget was not yet initialized.
Also fixed a redundant restoring of control state. Control states are already restored individually by setting SaveState to true.
> bugfix-JsCommandOrderAndRestoreState

- includes/base_controls/QPaginatedControl.class.php
Making paginated controls default to using ajax. This is now the modern approach and more responsive.
Did some cleanup in the __set function. It should not set blnModify for anything that comes in, because it might be passing the __set call onto the parent control. Removed return values from __set, since they are ignored by PHP, so having them is confusing.
> bugfix-PaginatedControlCleanup

- assets/php/_devtools/jquery_ui_gen/jq_control.tpl.php
- assets/php/_devtools/jquery_ui_gen/jq_control_gen.php
- includes/base_controls/QAccordionGen.class.php
- includes/base_controls/QAutocompleteGen.class.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QDatepickerBoxGen.class.php
- includes/base_controls/QDatepickerGen.class.php
- includes/base_controls/QDialogGen.class.php
- includes/base_controls/QDraggableGen.class.php
- includes/base_controls/QDroppableGen.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QJqButtonGen.class.php
- includes/base_controls/QJqCheckBoxGen.class.php
- includes/base_controls/QJqRadioButtonGen.class.php
- includes/base_controls/QMenuGen.class.php
- includes/base_controls/QProgressbarGen.class.php
- includes/base_controls/QResizableGen.class.php
- includes/base_controls/QSelectMenuGen.class.php
- includes/base_controls/QSelectableGen.class.php
- includes/base_controls/QSliderGen.class.php
- includes/base_controls/QSortableGen.class.php
- includes/base_controls/QSpinnerGen.class.php
- includes/base_controls/QTabsGen.class.php
Going back to the old method of returning code in the GetEndScript function. Doing this for a few reasons:
- We need a way to ensure that javascript widgets are attached before we start executing code on them. GetEndScript is really the place to do this.
- ExecuteCommandScript is really designed to execute code on a widget that is already attached. The widget attachment process should not use that function to attach itself.
- The .off() function needed to be executed before any other code. This ensures that will happen before sending javascripts to the controls.
In the process, I had to regenerate the JQueryUI controls, and fix a small problem in the generation due to a change in the jQuery Doc website.
I also added some additional commenting and pretty-printing to the developer output.
> bugfix-GetEndScript

- assets/php/error_dump.php
Assert strings are already encoded, and so am getting double-encode error messages for asserts. This will prevent that.
> bugfix-AssertErrors

- includes/codegen/QCodeGenBase.class.php
Overriding class name not being used in code generation.
> bugfix-CodeGenClass

- includes/qcubed/_core/database/QSqlServer2005Database.class.php
Please see link below for issue description.
[Issue 692 - Description Link](https://github.com/qcubed/framework/issues/692)
> Pull Request for - QSqlServer2005Database.class.php - Codegen fails if the table has no index column and no primary key (Issue #692)

- includes/base_controls/QDateTimePicker.class.php
Added the AllowBlankTime, AllowBlankDate, TimeSeparator, SecondInterval, MinuteInterval and HourInterval property.
**AllowBlankTime** and **AllowBlankDate** can be used to remove the ```--``` entry from the DateTimePicker. This is helpful where we have to force the user to enter valid time. 
**TimeSeparator** allows you to select the character used for separate time.
**HourInterval**, **MinuteInterval** and **SecondInterval** allow the developer to select intervals that he wants to let the user select from (e.g. I want to allow selection of time only in intervals of 10 minutes).
These properties allow us to escape a lot of validation logic at times when extreme strictness is not required but certain rules (which are obvious by these properties) are helpful.
> Added a few useful properties to QDateTimePicker

- includes/base_controls/QFormBase.class.php
The JS environment variables that describe the paths to the various assets were getting put up after the ready function, and so were not available for use by the control and plugin javascript files. This moves just after qcubed.js is included. It also fixes a problem where they were not including the subdirectory define.
> bugfix-JsEnvironmentVariables

- assets/js/qcubed.js
Follow up to bugfix-EmptyCheckLists.
Some versions of PHP do not send a variable with no '=' sign to the $_POST array. This fixes that.
> bugfix-EmptyCheckLists2

- assets/php/_devtools/plugin_manager.php
- assets/php/_devtools/plugin_manager.tpl.php
Completing the removal of the old installer. 
Commented out old code instead of removing it. Potentially the installer could be reworked to directly call the composer command, but its not so easy because people can set up composer in different ways. We somehow have to capture how the user executes the composer command in order to automate the process. Or, we call into github using the github api and bypass composer.
> bugfix-PluginManager

- includes/codegen/templates/db_orm/class_gen/property_get.tpl.php
- includes/codegen/templates/db_orm/class_gen/qcubed_query_classes.tpl.php
Allowing references to type tables to be directly accessed through the referencing tables. This will permit type tables to more easily be displayed in datagrids, and save typing when trying to get the value of a type.
> feature-TypeTableReference

- assets/php/_devtools/start_page.php
Refering to the form_drafts in dev-tools so that when you need to recreate the entire directory, you don't have to select out the index.php file in there.
> bugfix-FormDraftsLocation

- assets/php/examples/advanced_ajax/CalculatorWidget.tpl.php
- assets/php/examples/dynamic/control_proxy.tpl.php
- assets/php/examples/events_actions/event_delegation.php
- assets/php/examples/other/datagrid_connectors.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QControlProxy.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QPaginatorBase.class.php
- includes/base_controls/_actions.inc.php
Changing QControlProxy to use a jQuery .on function to be more efficient. 
Changing API to be easier to use a proxy and more obvious on how to embed it in a tag.
Fixing examples to reflect changes.
> feature-QControlProxyImprovements

- assets/php/_devtools/codegen.php
- includes/codegen/QCodeGenBase.class.php
- includes/codegen/QDatabaseCodeGen.class.php
Splitting warning and errors in the code-generation process to ensure that the aggregation system works if there are only warnings, not errors.
> Split warnings and errors generated in the code generation system

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QTag.class.php
- includes/base_controls/_actions.inc.php
- includes/base_controls/_utilities.inc.php
- includes/framework/QApplicationBase.class.php
- includes/framework/QHtml.class.php
Making Minimize into a QApplication global instead of a define so that controls can individually turn it on and off as needed.
The primary thing I am fixing is that in certain situations, like when html objects are styled with inline-block styling, the tabs and returns that are inserted to make the html look good will also add a 4px wide space between objects, causing different drawing when Minimize is on and off. This allows a particular control to always draw minimized so that doesn't happen.
> bugfix-Minimize

- .travis.yml
- assets/php/examples/mysql_innodb.sql
- assets/php/examples/pgsql.sql
- includes/codegen/QColumn.class.php
- includes/codegen/QDatabaseCodeGen.class.php
- includes/codegen/QTypeTable.class.php
- includes/codegen/templates/db_type/class_gen/_main.tpl.php
- includes/database/QMySqliDatabase.class.php
- includes/database/QPostgreSqlDatabase.class.php
- includes/framework/QQuery.class.php
- includes/tests/qcubed-unit/QTypeTests.php
Fixing problem for type tables where the resulting constant literals were always strings. They are now the correct PHP type of value, depending not he database type.
> bugfix-TypeTableLiterals

- includes/base_controls/QPaginatorBase.class.php
The paginator was showing the following with IndexCount as 10 and page number 6 (where 6 was the last page).
This pull request fixes the boundary condition failure.
> Fixed abnormal behavior on Paginator's boundary condition with intLeftBunchTrigger

- includes/database/QMySqli5Database.class.php
- includes/database/QMySqliDatabase.class.php
- includes/database/QPostgreSqlDatabase.class.php
- includes/database/QPostgreSqlPdoDatabase.class.php
- includes/database/QSqLite3PdoDatabase.class.php
Making Decimal values be PHP strings instead of floats. The whole purpose for decimals is precise tracking of fractions, and converting to floats completely looses that benefit. It also prevents using the bcmath library to do precision math with the Decimal number. If the developer wants a float, they should  just specify a float. Anyways, if the developer still wants a float, PHP will do the conversion automatically when it is used in a math operation.
> bugfix-DecimalType

- includes/codegen/QDatabaseCodeGen.class.php
Changing single-column index errors to warnings (because everything would still work). In my application, there are tables where I would not make a single-column search ever. A double-coulmn index serves the purpose and there are no performance drops anyway. 
Therefore, such a case should not stop the aggregation codegen templates from being run. This commit ensures the same.
> Changing single-column index errors to warnings 

- includes/base_controls/QHtmlAttributeManagerBase.class.php
- includes/framework/QApplicationBase.class.php
Changing the default to be the V2 way of redirecting. Defaulting to sending a javascript causes a number of other problems, including unexpected saves and screen flashes. Having a javascript way of doing is still important, but it is the exception more than the rule.
> bugfix-RedirectDefault

- includes/base_controls/QSimpleTableColumn.class.php
Trying to prevent really a type mismatch problem, making sure a callable is actually callable.
> bugfix-SimpleTableAssert

- assets/php/examples/qcubed_query/conditional_expand.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QSimpleTableColumn.class.php
- includes/codegen/templates/db_orm/class_gen/class_info.tpl.php
- includes/codegen/templates/db_orm/class_gen/instantiation_methods.tpl.php
- includes/codegen/templates/db_orm/class_gen/qcubed_query_classes.tpl.php
- includes/codegen/templates/db_orm/class_gen/qcubed_query_methods.tpl.php
- includes/codegen/templates/db_type/class_gen/_main.tpl.php
- includes/framework/QModelTrait.trait.php
- includes/framework/QQuery.class.php
- includes/tests/qcubed-unit/BasicOrmTests.php
- includes/tests/qcubed-unit/ExpandAsArrayTests.php
- includes/watchers/QWatcherBase.class.php
Refactor of the QQuery code. Does the following:
- Documenting functions
- Remove most warnings
- Removes the QQBaseNode. All nodes derive from QQNode.
- Creates the concept of a QColumnNode and QTableNode to differentiate leaf and stem nodes. This allows PHPs own type checking system to do some type checking.
- Moves Fields to the nodes to make them more available to the join code. Slight speed improvement as a result, but it at least avoids the need to do a function call on a variable named class.
- GetColumnAlias is not overloaded to also do the join of nodes. There is now a Join function. They are separate functions for better understanding, and so that GetColumnAlias will only apply to column nodes and not table nodes.
- Adds the ability to sort on a reverse reference node.
- Fixes a …
> feature-QQueryRefactor

- assets/js/qcubed.js
Fixing problem that occurs when trying to execute a javascript function that does not exist. Doing so will bring down the rest of the javascript on the page. We check to see if the javascript function exists before executing.
> bugfix-ExecuteMissingFunction

- includes/base_controls/QPaginatorBase.class.php
This variable is defined in the subclass only, but used in the superclass. This fix adds the definition to the superclass too.
> bugfix-PaginatorVariable

- includes/base_controls/QButtonBase.class.php
Allowing inner-html of button to be over-ridden. Useful for bootstrap buttons.
> feature-OverrideButtonDraw

- includes/base_controls/QDateTimePicker.class.php
QDateTimePicker was not picking up the right Date and Time from the browser because in the new system (version 3.0), we are sending the value of only those elements whose values have been changed. This resulted in a fail of the logic being used till version 2.2.
This pull request aims to fix that problem.
> BugFix for QDateTimePicker not detecting data changes

- includes/base_controls/QDataRepeater.class.php
Fixing problem with data repeater. If the data binder returns no data, the data repeater is removed from the dom. If the data binder then returns data later, the data grid will be placed back in the dom, but at the end of the form since there is no remnant of the data repeater to know where to put it.
> bugfix-EmptyDataRepeater

- includes/base_controls/QControlBase.class.php
Enables the support for forcing an element to be drawn as a block-level element if it has a wrapper. Also permits defining render methods with additional paramenters that are not related to overriding parameters.
> bugfix-ForceBlockElement

- assets/php/error_dump.php
- includes/error.inc.php
Fixing problems with HHVM when displaying error messages.
Also, note the following php.ini config setting:
``` hhvm.log.always_log_unhandled_exceptions = 0 ```
The default setting is 1, which will send all exceptions to the log file and will NOT execute the qcubed exception handler.
> bugfix-hhvmErrorHandling

- assets/php/tests/ui_basic.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QTextBoxBase.class.php
- includes/framework/QHtml.class.php
Fixing problem with submits of multi line text boxes. Extra lines were being added. This was caused by switching to HTML5 encoding. The fix is to convert \r\n combinations in post variables to a single newline.
This also fixes a potential security problem. Warnings and errors were being sent to the browser in the clear without encoding the text.
> bugfix-Multilne

- includes/base_controls/QDataGrid2Base.class.php
- includes/base_controls/QSimpleTableColumn.class.php
Prevents a checkbox click from bubbling as a row click. Also fixes some documentation.
> bugfix-DataGrid2ColumnCheckClick

- assets/js/qcubed.js
- includes/framework/JavaScriptHelper.class.php
Creating QJsFunction class to allow the results of a function call to be sent to JQueryUI object or other widget. One specific example is using the output of a function as the static list of items used by an autocomplete. There was really no other way to accomplish this.
Also, fixes a problem with QJsClosure to allow parameters to be other QJs... types.
> feature-QJsFunction

- includes/framework/QApplicationBase.class.php
Adding session_write_close to make sure recently updated session variables get written to the session before exiting for a redirect.
> bugfix-RedirectSessionVars

- includes/codegen/templates/db_orm/class_gen/qcubed_query_classes.tpl.php
- includes/codegen/templates/db_orm/panels/edit_create_objects.tpl.php
Fixing problem with list objects created by reverse reference items. If the object was set to not be included in the connector, the panel was still trying to create it.
> bugfix-ReverseReferenceCodegen

- includes/codegen/templates/db_orm/panels/edit_validate_unique.tpl.php
Fixing validation crash that happens when you override the creation of form objects such that all the objects are not created in the panel. This fix will check to make sure the object exists before trying to validate it.
> bugfix-UniqueValidationOnMissingFields

- includes/framework/QDateTime.class.php
- includes/tests/qcubed-unit/QDateTimeTests.php
Fixing an old problem where if you create a null QDateTime and specified you wanted it to be DateOnly, it would produce a non-null date at 2000-01-01. Same fix for TimeOnly too.
> bugfix-NullDateOnly

- includes/base_controls/QFormBase.class.php
Fixing regression bug. We still need a form class name in case another class is redirecting, like the QForm class. get_called_class will not return the correct class name in this situation.
> bugfix-FormId2

- includes/framework/QType.class.php
Allow magic method to stringify objects if one is set. Currently, you get an error, even if __toString() is defined on an object.
> bugfix-StringifyObjects

- assets/js/qcubed.js
Fixing problem where changes to radio button list were not being detected. The problem was the order of events being detected. This change ensures that our formObjChanged method will be called first.
> bugfix-RadioAndCheckListChange

- includes/base_controls/QCheckBoxList.class.php
- includes/base_controls/QRadioButtonList.class.php
Fixing problem where the visual state of jQueryUI buttons did not change, even though underlying value of buttons changed.
> bugfix-RadioAndCheckListRefresh

- assets/js/qcubed.js
- includes/base_controls/QControlBase.class.php
Fixing RenderWithError and RenderWithName code so that it does not repeatedly draw warnings and errors when updated via ajax when using controls without wrappers. I removed the "hasrel" data attribute in the process, it was not needed, and also could not be relied on to be included in the html. Changed the "rel" data tag to "qrel" to avoid potential name conflict if user used a "rel" data tag.
> bugfix-hasrel

- install/project/includes/configuration/configuration.inc.sample.php
Fixing comment to correctly size the id field for DbBackedSession tables
> bugfix-DbBackedSessionTableComment

- assets/php/_devtools/codegen.php
- composer.json
- includes/framework/QInstallationValidator.class.php
Codegen complains for new project
Codegen complains that:
```
Unable to mkdir /var/www/example.com/project/forms
Unable to mkdir /var/www/example.com/project/includes/panel
Unable to mkdir /var/www/example.com/project/includes/dialog
```
These directories should pre-exist in an install/project/ directory with write rights requested in composer file, and `assets/php/_devtools/config_checker.php` should check it's existance and write rights.
> Fixes the #856 issue

- .travis.yml
ATTENSION! It would break tests! The reason is that they are really broken on PHP 5.5 at minimum.
> fixes issue #858 (Tests fails on PHP 5.5)

- assets/php/examples/other_controls/persist.php
- includes/base_controls/QFormBase.class.php
- includes/framework/QApplicationBase.class.php
The current system has a problem, in that QApplication::Redirect will not save control states unless you add false as a second parameter. This fix will allow persistent controls to be saved even if you forget to do this.
> bugfix-PersistantControlsAndRedirect

- includes/codegen/controls/QDataGrid2Base_CodeGenerator.class.php
- includes/codegen/templates/db_orm/panels/_list_subclass.tpl.php
This is an important enhancement to the ListConnector generator I created recently. After using it for a while, I found it too limiting.
The problem is as follows:
We create a QDataGrid2 subclass to list the contents of a table. We then embed that data grid into a panel, which contains a filter, a new button, and anything else the developer might add to the list view. In some situations, the data grid can be thought of as a rather static view into the table that the developer would want to show with one particular set of columns and conditions, and reuse. In other situations, the developer would want to customize the columns and conditions for different views into the data. 
This new way of generating the list code accommodates both situations. The developer can either override functions …
> feature-ListColumns

- includes/qcubed.inc.php
We usually run all qcubed applications in a webbrowser. But sometimes I'd like to write scripts with qcubed that I run on the command line. 
When executing a script on the command line, it makes little sense to buffer the output. You actually want the output straight away. 
I don't know if this change belongs in the core of qcubed, but I can't see how to change this in another manner.
> Don't use output buffering when on cli

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QDialogBase.class.php
- includes/base_controls/QFormBase.class.php
Making any control auto-renderable like dialogs. This is needed for the new bootstrap modal class, and can be used by any future windowing type feature.
> feature-AutoRender

- includes/base_controls/_actions.inc.php
Fixing bug where events defined in namespaces were not working. The problem was that backslashes used in defining the namespace path were being removed by the javascript side.
> bugfix-NamespacedEvents

- includes/framework/QApplicationBase.class.php
Preventing someone from specifying a database number of zero by accident, since it conflicts with some things in the framework.
> bugfix-ZeroDB

- includes/base_controls/QFormBase.class.php
Adds the ability to reset validations states at any time. This is needed for dialogs, because they are sometimes closed without generating an event, and they need to reset validation states at this time.
> bugfix-ResetValidationStates

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QHListControl.class.php
Fixing problem with subclasses of QHListControl not being able to call functions correctly because of the unnecessary limit on the control type. Needed for work I am doing in the bootstrap plugin.
> bugfix-HListItemParam

- includes/base_controls/QListBoxBase.class.php
- includes/base_controls/QListItemManager.trait.php
Minor listbox issue. Making sure item exists before setting it as the listbox selected value. Fixes a problem where if the current selection is deleted, then there will be no selection, rather than the default selection. Listboxes should always have something selected when possible.
> bugfix-RestoreListboxState

- includes/base_controls/QSimpleTableBase.class.php
- includes/base_controls/QSimpleTableColumn.class.php
A multi-purpose column to display anchor tag links. An answer to the "Edit" column that is now deprecated from QDataGrid. This column is much more flexible, but still very easy to use. Can accommodate  static text, property chains, multi-dimensional arrays,  and callbacks to use as the label, the destination, the GET variables, or the anchor tag attributes. Can display a QControlProxy. Can be configured to display a minimal link such that a QOnEvent can be used to trap the bubbled up click if needed.
> feature-QSimpleTableLinkColumn

- install/project/includes/configuration/configuration.inc.sample.php
Umlauts problem is always a problem! In English language not problem.
This correction allows umlauts in the database to display correctly.
What do you think of this?
> Proposal to add encoding "UTF-8" to Database Connection

- includes/codegen/QModelConnectorEditDlg.class.php
Fixing problem with connector dialog. This is caused by earlier changes to how nodes work. It was no longer identifying direct foreign keys, and so could not load the right kind of controls.
> bugfix-ConnectorDialog

- includes/base_controls/QFloatTextBox.class.php
- includes/base_controls/QIntegerTextBox.class.php
- includes/base_controls/QTextBoxBase.class.php
There are ways to circumvent Validate, even accidentally. Overriding the Value attribute to return a sanitized version of the text box.
> bugfix-NumericValue

- assets/js/qcubed.js
- assets/php/tests/ui_ajax_timing.php
- assets/php/tests/ui_ajax_timing.tpl.php
Fix to a timing problem with checkboxes. This issue was probably the original reason for a checkbablecontrols hidden input and handler.
The problem is that for checkboxes and radio buttons, a "click" event is equivalent to a "change" event for our purposes. We want to be able to attach a click event to a checkbox, and during the action, see that the checkbox has changed. This was not happening for ajax handlers because the click would fire before the change, and so we would not post the change until the next ajax event.
This fix detects clicks on checkboxes and radio buttons, and then registers them as changed so that we send the value of the checkbox or radio button to the server along with any other event handlers.
This includes some test code to make sure it is working. The test was …
> bugfix-CheckboxAjaxClickTiming

- assets/js/qcubed.js
- assets/php/tests/ui_basic.php
- includes/base_controls/QCheckBox.class.php
- includes/base_controls/QRadioButton.class.php
Fixing up some minor issues:
- Setting attributes of checkboxes to values such that the value does not change should not cause a redraw.
- Setting the checked state of both radios and checkboxes is now handled with javascript, so no redraw needed here either.
> bugfix-CheckableControlSetting

- includes/base_controls/QDataGrid2_CheckBoxColumn.class.php
Hiding the CheckAll box by default, because the box requires the column to be subclassed when this box is visible. This allows the column to be used as a simple checkbox column that has no preliminary state, and you just want to see what got checked, without having to subclass the column.
> bugfix-DataGridCheckColumnWithNoOverride

- includes/codegen/QDatabaseCodeGen.class.php
- includes/codegen/QReference.class.php
- includes/codegen/templates/db_orm/class_gen/instantiation_methods.tpl.php
- includes/tests/qcubed-unit/BasicOrmTest.php
There is a problem in how expansions are done currently, in that when you expand on a foreign key, and then with the object, look across the foreign key, and then look back, you see a null, which causes a Load to happen, and which loads a copy of the object looking backwards.
In other words, 
```
$clauses = [QQ::Expand(QQN::Person()->ProjectAsManager)];
$objPerson = Person::QuerySingle(QQ::All(), $clauses);
$objProject = $objPerson->ProjectAsManager;
$objPerson2 = $objProject->ManagerPerson;
```
$objPerson2 is not the same as $objPerson, plus an extra hidden query gets executed to fill in ManagerPerson when you ask for it. This can make some tables very slow to load, and make complex relationships difficult to manage.
This pull request fixes things so that $objPerson2 will be a reference …
> bugfix->ReverseReferencesOfForwardExpansions

- includes/codegen/templates/db_orm/class_gen/qcubed_query_methods.tpl.php
- includes/framework/QModelTrait.trait.php
Fixes QueryArray and QuerySingle so that the correct return type for each object will be put in the phpdoc comments. Makes is easier to use in editors.
> bugfix-QueryArrayAndSingleReturnTypes

- assets/php/error_dump.php
- includes/base_controls/QControlBase.class.php
Fixing situations where a control might not be exportable. QCubed will just fail silently in these situations. This fix restores QCubed's ability to catch certain errors. It also fixes the problem where HHVM can't export controls.
> bugfix-VarExport

- assets/php/examples/mysql_innodb.sql
- assets/php/examples/pgsql.sql
- assets/php/examples/qcubed_query/qqselect.php
- includes/base_controls/QSimpleTableColumn.class.php
- includes/codegen/templates/db_orm/class_gen/_main.tpl.php
- includes/codegen/templates/db_orm/class_gen/virtual_attribute.tpl.php
- includes/database/QPostgreSqlDatabase.class.php
- includes/database/QPostgreSqlPdoDatabase.class.php
- includes/framework/QDatabaseBase.class.php
- includes/framework/QModelTrait.trait.php
- includes/framework/QQuery.class.php
- includes/tests/qcubed-unit/BasicOrmTest.php
- install/project/includes/configuration/configuration.inc.sample.php
Consolidating the conversion of virtual aliases so they are consistent wherever they are used.
Changes to:
- Make aggregation clauses the same as virtual attributes in every way
- Use virtual attributes in order by clauses as aliases
- Add string functions to math and func nodes
- Kill uneeded terminating php tag
- Unit test
- Fixing test problem with aggregate clauses, that revealed additional problems around the issue of OnlyFullGroupBy databases.
Changed PostgresSql to be OnlyFullGroupBy by default.
Added a database adapter option so you can override the default when you set up the adapter.
Fixing error related to problem with precision in database declaration. MYSQL standard says specifying DECIMAL with no precision should result in zero decimal places. POSTGRESQL ignores the …
> bugfix-VirtualAttributeClauses

- includes/base_controls/QControlBase.class.php
Control templates are searched for in the same location as the form include file that they are included in.
This fix places the control template in the same directory as the control definition file if no path is specified.
> bugfix-ControlTemplateLocation

- assets/js/qcubed.js
- assets/php/tests/ui_postvars.php
- assets/php/tests/ui_postvars.tpl.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QImageBase.class.php
- includes/base_controls/QImageControlBase.class.php
- includes/base_controls/QImageLabelBase.class.php
- includes/framework/QApplicationBase.class.php
- includes/framework/QRssFeed.class.php
- includes/framework/QSoapService.class.php
Fixing a number of problems with character encoding that is not UTF-8. I think I have it working so that all variables are unpacked into the same encoding as QApplication::$EncodingType. Tricky stuff.
I would like some people to verify this before committing it, so consider this a work in progress.
In particular, please open the file vendor/qcubed/framework/assets/php/tests/ui-postvars.php in a browser and try it out. Someone please try it in IE. Also, try changing the encoding type at the top of the file to something like cyrillic and test again.
I am concerned in particular about the ability of JSON.stringify to encode non- utf-8 strings, and then have those strings get past through the server submit and ajax submit processes. Some help testing this would be appreciated.
> bugfix-characterEncoding

- includes/tests/qcubed-unit/BasicOrmTest.php
- includes/tests/qcubed-unit/CacheTest.php
- includes/tests/qcubed-unit/ExpandAsArrayTest.php
- includes/tests/qcubed-unit/ModelConnectorTest.php
- includes/tests/qcubed-unit/QCssTest.php
- includes/tests/qcubed-unit/QDatabaseTest.php
- includes/tests/qcubed-unit/QDateTimeTest.php
- includes/tests/qcubed-unit/QI18nTest.php
- includes/tests/qcubed-unit/QQAliasTest.php
- includes/tests/qcubed-unit/QStringTest.php
- includes/tests/qcubed-unit/QTimerTest.php
- includes/tests/qcubed-unit/QTypeTest.php
- includes/tests/qcubed-unit/QUnitTestCaseBase.php
Reversing asserEquals calls so that the expected value is first. Fixes #987.
> bugfix-AssertEquals

- assets/js/qcubed.js
- includes/base_controls/_actions.inc.php
- includes/qform_state_handlers/QDbBackedFormStateHandler.class.php
- includes/qform_state_handlers/QFileFormStateHandler.class.php
- includes/qform_state_handlers/QFormStateHandler.class.php
- includes/qform_state_handlers/QSessionFormStateHandler.class.php
This adds the ability to send ajax events to the server asynchronously. By default, multiple ajax events are queued, and each one can not fire until the previous one returns a result and the result is processed. The primary reason for this is to allow the formstate to be refreshed.
However, there are times when you don't want to wait:
1. You are using a formstate handler that reuses the same formstate key for ajax events (the db handler does this now.) So, you know the formstate key is not going to change between ajax calls.
2. You are rapidly sending ajax events to give quick user feedback.
> feature-AsyncAjax

- includes/base_controls/QSimpleTableColumn.class.php
Fixing problem where a '0' style is inserted if there is no style. A result of "explode" returning an array even when there are no delimiters found in the string.
> bugfix-StyleRender

- assets/js/qcubed.js
- includes/base_controls/QCheckBoxList.class.php
Fixing problem detecting an empty checkbox list. An empty array was not being sent through to the server.
> bugfix-EmptyCheckBoxList

- includes/base_controls/QRadioButtonList.class.php
Fixing refresh problem. This fix prevents the radio list from refreshing again when reading a change from the browser.
> bugfix-RadioListRefresh

- includes/base_controls/QHtmlTableBase.class.php
Initializing columns to an empty set to prevent errors when drawing an empty table.
> bugfix-EmptyTableErrors

- includes/codegen/templates/db_orm/model_connector/refresh_methods.tpl.php
- includes/codegen/templates/db_orm/panels/edit_load.tpl.php
Fixing problem with trying to load a record that does not exist in the database. This would eventually cause an assertion failure in Refresh. Loading a record that does not exist should be an expected thing to happen, as there are situations where someone could load a record that was just deleted by a different user, so we need to fail more gracefully.
> bugfix-BadRecordIdLoad

- includes/base_controls/QControlBase.class.php
- includes/base_controls/QFormBase.class.php
Fixing problem where items that are changed after state is saved, like if the data was taken from a QueryString, were not getting saved.
Scenario is this:
```
public function Form_Create() {
$txtName = QTextBox($this);
$txtName->SaveState = true;
if (QApplication::QueryString('name')) {
$txtName->Text = QApplication::QueryString('name');
}
}
```
QueryString text in this case was not being saved, and coming back to the form did not restore it when the form did not have the query string.
> bugfix-SaveState

- includes/codegen/templates/db_orm/class_gen/object_delete.tpl.php
- includes/codegen/templates/db_orm/class_gen/object_save.tpl.php
For the datagrid header links and the paginator controls, use "javascript:;" instead of "#" in the links so that the "#" isn't added to the querystring. The "#" can cause problems when navigating through the application.
> Change "#" to "javascript:;" in HREF tag

- includes/framework/QDbBackedSessionHandler.class.php
The base64 encoder was at sometimes producing a null result, which was causing the session to be dropped. This new version relies on a binary column instead of a text column and encrypts and compresses the data instead. This results in much more compact data with no dropped sessions and better security.
> bugfix-QDbBackedSessionHandler

- includes/base_controls/QFormBase.class.php
Another attempt at fixing the save state problem. This was is fixing an ajax draw problem. We were exiting prematurely and not calling the SaveControlState or the Form_Exit methods.
> bugfix-SaveState2

- README.md
- assets/php/_devtools/config_checker.php
Fixes #1072 for now.
Also, I strongly suggest that we put `ezyang/htmlpurifier` in the *require* section in composer.json. 
Not doing so breaks the QCrossScripting with textboxes and is not a pleasant thing, especially for a newbie. Since we are using the library in our code and it is anyways compatible (license-wise), why not install it right away? 
**Additional Note**: We have tested the PHP7 functionality in our organization with the project where we are using the framework. It is not causing any issues right now. Hence, I have added the PHP7 support in Readme and Start pages.
> Fixing Installation messages

- includes/database/QPostgreSqlDatabase.class.php
- includes/framework/QDbBackedSessionHandler.class.php
The #1077 PR broke the DbBackedSessionHandler for PostgreSQL. This one re-establishes the support and enables BLOB support in general for PostgreSQL.
> Blob Support for PostgreSQL - General and Session Handler

- includes/base_controls/QDataGrid_CheckBoxColumn.class.php
For example, to pre-check some rows if user already checked them earlier and results were saved to the database.
> This method is useful for client code

- includes/framework/QDateTime.class.php
Fixing an HHVM problem. HHVM was choking on the constructor inside the __wakeup call. Implementing this using the more modern Serializable interface seems to have fixed it. This has the benefit of making it serializable in other situations too.
> bugfix-DateTimeSerialization

- includes/framework/QDbBackedSessionHandler.class.php
Fixing a problem caused by saving an empty session while the encryption and compression tags were off. Some other cleanup as well.
> bugfix-EmptySession

- assets/php/error_dump.php
Preventing the error page from crashing when USER AGENT is not sent (many mobile apps don't send the USER AGENT).
> TO prevent error page from crashing if the HTTP USER_AGENT is not sent

- includes/framework/QCryptography.class.php
- install/project/includes/configuration/configuration.inc.sample.php
Here is the list of changes done:
- Remove the mcrypt module functions and the corresponding object being used in the file.
- Change the default algorithm to AES-265
- Change the default mode from ECB to CBC
- Set a default IV for QCryptography to maintain the backward compatibility with simple initializations like `$objCrypto = new QCryptography();`
- Remove the RandomSource and Mode option and instead allow the user to put in an IV string by his own.
- Moved the default Cipher name, Key and IV to be used in the configuration file. This is to make sure that subsequent framework upgrades do not override user defaults and the user does not need to override a core class just for the sake of changing defaults of his cipher of choice. 
This PR is for #1088 .
> QCryptography Updated

- includes/framework/QDbBackedSessionHandler.class.php
- includes/qform_state_handlers/QDbBackedFormStateHandler.class.php
- install/project/includes/configuration/configuration.inc.sample.php
Implementing new QCryptography class in the handlers.
Also improves the issue we had with PG and binary data, leaving Base64 on as default for placing in a TEXT field, but giving the option to remove it, and still have it work with PG. (I should have thought of this approach earlier :{
> bugfix-DbBackedHandlersEncryption

- includes/framework/QDateTime.class.php
if date is earlier then this "zero" date, the resulting QDateTime object is invalid
My problem was that date obtained from mysql was just `0000-00-00 00:00:00` - essentially zero date. It leads to datetime displayed as `Nov 30 -0001 12:00 AM`. This patch fixes it.
> Fixes parsing date before 1970-01-01 00:00:00

- includes/framework/QInstallationValidator.class.php
- install/project/includes/configuration/configuration.inc.sample.php
- travis/configuration.inc.php
1. docs for `APP_` defines
2. commented out `APP_` defines
In installation verificator script directories are checked only if corresponding `APP_` defines are actually defined. User is free to uncomment and use them.
> Issue 1040 app defines

- includes/qcubed/_core/framework/QQuery.class.php
You only need to wrap a subsql statement with braces (  ) when it is an actual query. 
For example: 
`SELECT * FROM table1 WHERE col1 = (SELECT count(id) FROM table2)`
If you want to use QSubSql for something other that pure queries, you can run into problems.
For example: 
```
Client::QuerySingle(
QQ::All(),
QQ::Clause(
QQ::Count(QQ::SubSql('DISTINCT t0.client_id'), "count_clients")
)
);
```
Will generate
`SELECT COUNT( (DISTINCT client_id) ) as distinct_client_count FROM client;`
but that is invalid sql, it should be
`SELECT COUNT( DISTINCT client_id ) as distinct_client_count FROM client;`
Without the braces ( )
> QSubSql generates invalid sql in some cases.

- assets/css/styles.css
- includes/base_controls/QDataGridBase.class.php
Fixing wrapping problem with sort icon. This keeps sort icon to the right of the text when title of a column is wrapped.
> bugfix-SortIcon

- includes/base_controls/QListItemManager.trait.php
- includes/codegen/QDatabaseCodeGen.class.php
- includes/framework/QDateTime.class.php
PHP 7.2 is now in the nightly build and is causing Travis to fail. The problems are two things:
count() does not handle a null value as an array. This uncovered a problem in code generation in the column analyzer.
Also, DateTime::setTime added a microsecond parameter.
> bugfix-php72

- includes/codegen/templates/db_orm/class_gen/property_set.tpl.php
- includes/framework/QCryptography.class.php
- includes/tests/qcubed-unit/BasicOrmTest.php
Fixing a regression problem from recently added setters and getters. I needed to make sure references are set in such a way as to be sure to update related ids, and also set the related object after setting the id, since setting the id will make the related object null.
> bugfix-CodeGenReferenceSet

- includes/framework/QAbstractCacheProvider.class.php
- includes/framework/QCacheProviderAPC.class.php
- includes/framework/QCacheProviderLocalMemory.class.php
- includes/framework/QCacheProviderMemcache.class.php
- includes/framework/QCacheProviderNoCache.class.php
- includes/framework/QDatabaseBase.class.php
- includes/framework/QMultiLevelCacheProvider.class.php
- includes/tests/qcubed-unit/CacheTest.php
- includes/tests/qcubed-unit/QDatabaseTest.php
Ensure that we implement expiration timeout to **existing** caches. 
This is quite useful and lays out the ground-work for implementing Redis as a cache provider.
> Ensure that we implement expiration timeout to existing cache providers

- .travis.yml
- composer.json
- docs/Caching/README.md
- docs/Caching/Redis.md
- docs/README.md
- includes/framework/QCacheProviderRedis.class.php
- includes/qcubed.inc.php
- includes/tests/qcubed-unit/RedisCacheTest.php
- install/project/includes/configuration/configuration.inc.sample.php
Basic Redis Cache provider built. I have used this in my project and is working fine. 
This Cache Provider has an additional setting for "TTL". Unlike other Caching systems which we have used till now within QCubed do not *persist* data. They use LRU mechanism and are definitely cleared after server restarts. While there is a way to use Redis as a LRU cache (like memcached), the default behavior of redis is to act like a persistent KV store. Also, not everyone is going to run redis as a LRU cache. Their redis installation may not use LRU settings, and in such cases depending on the server's configuration can be troublesome (can fill disk and keep old objects in cache forever). For such cases, the server should clear the contents automatically after some time. I assume caching things for …
> Basic Redis Cache provider built

- includes/codegen/templates/db_orm/class_gen/instantiation_methods.tpl.php
Fixing new problem with PHP nightly - asserts using strings for testing has been deprecated. There are other ways to turn off asserts, like with assert_options, or .ini file directives.
> bugfix-assertDeprecation

- includes/codegen/templates/db_orm/class_gen/class_initialize.tpl.php
- includes/codegen/templates/db_orm/class_gen/instantiation_methods.tpl.php
- includes/tests/qcubed-unit/QQFuncTest.php
- includes/tests/qcubed-unit/QQMathOpTest.php
Allows bypassing the initializer when reading objects from the database. The problem with that is you might only want to read a partial object using a QSelect clause, but the initializer will override this partial read, and you won't be able to tell what was read, and what was initialized. The new code allows the Initializer to be bypassed when reading objects from the database.
> bugfix-InitializingModels

- includes/codegen/templates/db_orm/class_subclass/_main.tpl.php
I wouldn't tell the user to use __toString as a function call, I don't think it's a good idea to be calling it like that.
> Legacy documentation __toString removed

- includes/framework/QCryptography.class.php
The '=' character is padding character in raw base64 encoded string.
It is removed in the QString::Base64UrlSafeEncode method (or the same implementation
in QCryptography class earlier). When trying to use base64 encoding built into
QCryptography class, the decryption fails because the base64 encoded data will
eventually lack the delimiting character.
The ':' character is outside the base64 character set and thus, when encoding,
the delimiter would not be lost.
I am facing that as a major issue with `=`. Changing it to `:` makes it work.
> Changed delimiter for Iv and Hashkey

- README.md
- includes/codegen/QDatabaseCodeGen.class.php
- includes/codegen/templates/db_orm/class_gen/_main.tpl.php
- includes/codegen/templates/db_orm/class_gen/object_save.30.tpl.php
- includes/codegen/templates/db_orm/class_gen/protected_member_variables.tpl.php
- install/project/includes/configuration/codegen_settings.xml
In preparation for 3.1 release, this adds backwards compatibility with 3.0 projects and adds a documented path to migrating code to 3.1 for the privateColumnVars feature.
> feature-30compatibility

- includes/base_controls/_actions.inc.php
Adding an assert for new QCubed users to prevent them from adding an action to a control that has not been added to a form.
> bugfix-AssertControlId

- assets/php/examples/datarepeater/ajax.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QDataRepeater.class.php
- includes/base_controls/QHtmlTableBase.class.php
- includes/base_controls/QHtmlTableColumn.class.php
- includes/framework/QType.class.php
Adding a "CallableType" type to QType to make type checking on Callables more consistent, and to help with the process of making sure a callable is serializable into the form state (not all callable types are).
Also, went through the code and fixed places where callables were not be correctly serialized.
This has a possible breaking change in that the QDataRepeater callbacks should use a standard callable when referring to function in the QForm, rather than just a string for a function name. This change makes the managing of the callable more standard with QCubed overall and how PHP currently lets you specify callbacks that are methods in objects.
> bugfix-Callable

- assets/js/qcubed.js
- assets/php/examples/advanced_ajax/dialog_box.php
- includes/base_controls/QControlBase.class.php
- includes/base_controls/QDialogBase.class.php
- includes/base_controls/QFormBase.class.php
- includes/base_controls/QListBoxBase.class.php
- includes/base_controls/_enumerations.inc.php
- includes/codegen/templates/db_orm/dialogs/_edit_dlg_subclass.tpl.php
- includes/codegen/templates/db_orm/dialogs/dlg_constructor.tpl.php
- includes/framework/QApplicationBase.class.php
Makes a number of impovements and fixes some issues with dialogs:
- Allows dialogs to be created on the fly rather than needing to have it be in the form
- Fixes a probem where you couldn't trap the QDialog_CloseEvent because the dialog was already closed.
- Fixes unnecessary redraws when bringing a dialog on to the screen from a validating button.
- Adds a feature that lets you set an event that will execute after all other ajax actions are complete, even if some of those ajax actions create new ajax actions.
> bugfix-DialogImprovements

- assets/php/examples/more_codegen/optimistic_locking.php
- assets/php/examples/mysql_innodb.sql
- includes/codegen/templates/db_orm/class_gen/object_save.tpl.php
- includes/codegen/templates/db_orm/dialogs/_edit_dlg.tpl.php
- includes/codegen/templates/db_orm/dialogs/dlg_button_click.tpl.php
- includes/codegen/templates/db_orm/dialogs/dlg_create_buttons.tpl.php
- includes/codegen/templates/db_orm/dialogs/dlg_save.tpl.php
- includes/codegen/templates/db_orm/forms/edit_button_click.tpl.php
- includes/codegen/templates/db_orm/model_connector/save_object.tpl.php
- includes/codegen/templates/db_orm/panels/_edit_base.tpl.php
- includes/codegen/templates/db_orm/panels/edit_load.tpl.php
- includes/codegen/templates/db_orm/panels/edit_refresh.tpl.php
- includes/codegen/templates/db_orm/panels/edit_save.tpl.php
- install/project/includes/controls/QWatcher.class.php
For too long has QCubed issued optimistic locking errors for back button presses on the browser, or multiple people editing a record.
This fix does the following:
- Puts dialogs in to the codegenned forms and dialogs to correctly detect optimistic locking errors and asks users what to do when a record has changed that the user is editing.
- Prevents the Back button on the browser from causing an Optimistic Locking error by making sure changes are posted to the form before proceeding to the next page. 
- Fixes examples page to work
- Fixes the default QWatcher to work on initial installation, which is needed for forms that use a dialog to do edits.
- Wraps Update code in transactions in situations where an update requires changes to multiple tables. This prevents data corruption and …
> bugfix-OptimisticLockingIssues

- includes/framework/QCryptography.legacy.class.php
- includes/qcubed.inc.php
Adding old cryptography class as a legacy class so that prior encrypted data can still be unencrypted.
I could not get the openssl library to decrypt the old DES-ECB encryptions that were the default of our old mcrypt version. So, we still need the old class.
> bugfix-QCryptoLegacy.

- includes/codegen/QDatabaseCodeGen.class.php
Fixing error message that incorrectly reported a problem with an index. Any number of issues with a table would cause it to not get included in the code generation, which would cause thrown exceptions instead of simple error messages in the output. This fix adds the error messages to the thrown exception so the user knows exactly why code generation could not proceed.
> Bugfix-TableGenError

- includes/codegen/templates/db_orm/class_gen/json_methods.tpl.php
- includes/database/QMySqli5Database.class.php
- includes/database/QMySqliDatabase.class.php
- includes/database/QPostgreSqlDatabase.class.php
- includes/framework/QDatabaseBase.class.php
Moves special handling of flags to SetFieldType. Makes a Blob type in PHP more akin to a Binary type. Text and VarChars are now both Text types in PHP, since PHP really doesn't care how the text is saved in the database. Improves the generated iterator.
> bugfix-BinaryType

- includes/codegen/templates/db_orm/class_gen/instantiation_methods.tpl.php
- includes/framework/QDatabaseBase.class.php
- includes/framework/QModelTrait.trait.php
- includes/tests/qcubed-unit/BasicOrmTest.php
Removes the dependency in the database adapters on the query builder. This is an important step to being able to move the database adapters to their own repository. Also adds a basic unit test for querying cursors.
> bugfix-RemoveQueryBuilderDependency

- includes/framework/QCacheProviderAPCu.class.php
- includes/qcubed.inc.php
The APCu interface has changed. Need to have an apcu only cache.
On PHP7 I was getting apc_fetch function not defined. Its been changed to apcu_fetch. We need the old one still because HHVM has not made the switch yet.
> bugfix-APCuCache.

- includes/base_controls/QControlBase.class.php
Removing the control was being called too many times for child controls. This is more efficient, in that child controls of child controls only get removed once.
> bugfix-RemoveChildControl

- includes/codegen/templates/db_orm/class_gen/property_get.tpl.php
- includes/codegen/templates/db_orm/class_gen/property_getters_setters.tpl.php
- includes/codegen/templates/db_orm/class_gen/property_set.tpl.php
Completing the move to getters and setters for all types of objects we are looking for.
Fixed a problem with Get(Prop)Array on array expansions. Trying to get the property was causing it to look for the corresponding "get" function, which was getting the data all over again, and ignoring conditional expansion data.
> bugfix-ModelGettersAndSetters

- includes/base_controls/QFormBase.class.php
We normally require file paths to be relative to DOCROOT. However, for ajax loaded files with absolute paths, we were adding in the __SUBDIRECTORY__ to qc.baseDir, causing these files to have the __SUBDIRECTORY__ twice.
Requires a change to QCKEditor.
> bugfix-AjaxJsAndCsIncludes

- includes/codegen/QModelConnectorEditDlg.class.php
Fixes QModelEditor to show a dialog that is a fixed height rather than one that varies, which is easier to edit.
> bugfix-ModelEditor

- includes/framework/QDbBackedSessionHandler.class.php
I needed this at work so I cleaned it up a bit. It was written in 2012 and was missing some documentation.
I added an example SQL CREATE statement for the database which makes it easier for users to get started with it.
I also removed the GetTables() in the Initialize because I don't think it's a good idea to do this every single request. It will crash anyway, and a database table won't just disappear...
I also moved the concatenation of the session_name with the session_id to a seperate function.
Let me know if this is ok.
> Cleaning up the QDbBackedSessionHandler

- includes/database/QMySqliDatabase.class.php
InsertOrUpdate is a great method that is currently only used by the dbsessionhandler. It allows you to remove a query to determine if you want to insert or update because mysql will do this for you. 
Unfortunately, when you use this method, you didn't get the LAST_INSERT_ID on insert. I added this, plus when there is a duplicate, qcubed will return the id found in the update. 
To simplify the INSERT statement I also used the alternative INSERT syntax. INSERT INTO tablename SET col=val in stead of INSERT INTO tablename (col) values(val)
I'm running dbbackedsessionhandler in production.and it sees no difference between the old and new function. So there shouldn't be an impact on the rest of qcubed.
> InsertOrUpdate now returns the autoincremented ID

- includes/qform_state_handlers/QFileFormStateHandler.class.php
Code fails attempting to unlink() the parent/self links.
> Ignore parent- and self-links when iterating Dir()

- includes/framework/QQuery.class.php
You cannot SUM or COUNT DISTINCT values using a GROUP BY with QCubed. Yes there is a DISTINCT, but not on an aggregated level.
To allow this, I've added a blnDistinct flag (by default this is FALSE to avoid breaking stuff).
You can now do 
`QQ::Sum(QQN::Task()->Time,"sum_time",true); // resolves to SUM(DISTINCT t0.time) AS sum_time`
`QQ::Sum(QQN::Task()->Time,"sum_time"); //-> still resolves to SUM(t0.time) AS sum_time`
> Adding Distinct flag to aggregated methods

- assets/php/_devtools/codegen.php
Some errors aren't fatal, and GenerateAggregate is perfectly capable of handling those errors (see issue #1249)
> Let GenerateAggregate run, even if we have errors

- assets/php/_devtools/installer/step_3.php
We should probably allow the user to copy paste the configuration if we can't write to it.
> Allow copy paste of configuration during install

- includes/framework/QString.class.php
Files or image file sizes in bytes are very uncomfortable to read or calculate. The function is created for human readability.
Example:
`$this->lblMessage->Text = 'Thanks for uploading the file: ' . $this->flaSample->FileName . ". File size: " . QString::DisplayByteSize($this->flaSample->Size, 2);`
> feature - DisplayByteSize

- includes/base_controls/QFormBase.class.php
$strFormId is useless. I think @spekary already tried to refactor some of it. 
With this commit I try to remove strFormId and pass the object itself. 
A possible use case is requesting a control by strControlId in a static method call. This is currently impossible, but after this commit you have the objFormId and can actually do this. 
I have also added a __toString() method in an attempt to save backwards compatibility. If someone does use the strFormId, it gets string cast automatically.
> $strFormId is useless
